# Generated by Django 5.2.5 on 2025-08-14 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inscricaoevento",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="inscricaoevento",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="evento",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="evento",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="parceriaevento",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="parceriaevento",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="materialdivulgacaoevento",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="materialdivulgacaoevento",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="briefingevento",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="briefingevento",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="feedbacknota",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="feedbacknota",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="historicalfeedbacknota",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="historicalfeedbacknota",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="tarefa",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="tarefa",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="tarefalog",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="tarefalog",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="eventolog",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="eventolog",
            old_name="modified",
            new_name="updated_at",
        ),
    ]
