# Generated by Django 5.2.5 on 2025-09-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0005_remove_avaliacao_feedback_from_inscricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
