# Generated by Django 5.2.5 on 2025-09-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0007_alter_evento_avatar_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="numero_presentes",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
