# Generated by Django 5.2.5 on 2025-09-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0009_seed_admin_group_event_permissions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MaterialDivulgacaoEvento",
        ),
    ]
