# Generated by Django 5.2.5 on 2025-09-22 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0010_delete_materialdivulgacaoevento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="briefingevento",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)), fields=("evento",), name="unique_active_briefing_per_event"
            ),
        ),
    ]
