# Generated by Django 5.2.5 on 2025-09-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0011_briefingevento_unique_active_briefing_per_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarefalog",
            name="tarefa",
        ),
        migrations.RemoveField(
            model_name="tarefalog",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="Tarefa",
        ),
        migrations.DeleteModel(
            name="TarefaLog",
        ),
    ]
