# Generated by Django 5.2.5 on 2025-09-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0011_briefingevento_unique_active_briefing_per_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="espera_habilitada",
        ),
        migrations.RemoveField(
            model_name="inscricaoevento",
            name="posicao_espera",
        ),
    ]
