# Generated by Django 5.2.5 on 2025-09-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0012_remove_evento_espera_habilitada_and_more"),
        ("eventos", "0012_remove_tarefalog_tarefa_remove_tarefalog_usuario_and_more"),
    ]

    operations = []
