# Generated by Django 5.2.5 on 2025-09-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0013_merge_20250925_1408"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="orcamento",
        ),
    ]
