# Generated by Django 5.2.5 on 2025-09-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0014_remove_evento_orcamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="briefing",
        ),
        migrations.DeleteModel(
            name="BriefingEvento",
        ),
    ]
