# Generated by Django 5.2.5 on 2025-09-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0015_remove_evento_briefing_delete_briefingevento"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="briefing",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="parcerias",
            field=models.URLField(blank=True),
        ),
    ]
