# Generated by Django 5.2.5 on 2025-09-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0017_remove_parceriaevento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Ativo"), (1, "Concluído"), (2, "Cancelado"), (3, "Planejamento")]
            ),
        ),
    ]
