# Generated by Django 5.2.5 on 2025-09-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0018_alter_evento_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="publico_alvo",
            field=models.PositiveSmallIntegerField(choices=[(0, "Público"), (1, "Nucleados"), (2, "Associados")]),
        ),
    ]
