# Generated by Django 5.2.5 on 2025-10-05 00:00
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0019_alter_evento_publico_alvo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="coordenador",
        ),
    ]
