# Generated by Django 5.2.5 on 2025-10-13 18:15

import eventos.validators
from django.db import migrations, models
from django.db.models import Q


def clear_external_files(apps, schema_editor):
    Evento = apps.get_model("eventos", "Evento")
    campos = ("briefing", "parcerias")
    for campo in campos:
        condicao = Q(**{f"{campo}__startswith": "http://"}) | Q(**{f"{campo}__startswith": "https://"})
        for evento in Evento.objects.filter(condicao):
            setattr(evento, campo, "")
            evento.save(update_fields=[campo])


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0020_remove_evento_coordenador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="briefing",
            field=models.FileField(
                blank=True, upload_to="eventos/briefings/", validators=[eventos.validators.validate_uploaded_file]
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="parcerias",
            field=models.FileField(
                blank=True, upload_to="eventos/parcerias/", validators=[eventos.validators.validate_uploaded_file]
            ),
        ),
        migrations.RunPython(clear_external_files, migrations.RunPython.noop),
    ]
