# Generated by Django 5.2.5 on 2025-10-14 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0021_alter_evento_briefing_alter_evento_parcerias"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="contato_email",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="contato_nome",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="contato_whatsapp",
        ),
    ]
