# Generated by Django 5.2.5 on 2025-10-14 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0022_remove_evento_contato_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="numero_convidados",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="valor_ingresso",
        ),
    ]
