# Generated by Django 5.2.5 on 2025-11-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0023_remove_evento_numero_convidados_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="valor",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
