# Generated by Django 5.2.5 on 2025-11-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0024_evento_valor"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="gratuito",
            field=models.BooleanField(default=False),
        ),
    ]
