# Generated by Django 5.2.5 on 2025-11-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0025_evento_gratuito"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscricaoevento",
            name="metodo_pagamento",
            field=models.CharField(
                blank=True,
                choices=[("pix", "Pix"), ("boleto", "Boleto"), ("faturar", "Faturar"), ("outro", "Outro")],
                max_length=20,
                null=True,
            ),
        ),
    ]
