# Generated by Django 5.2.5 on 2025-11-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0026_alter_inscricaoevento_metodo_pagamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inscricaoevento",
            name="observacao",
        ),
        migrations.AlterField(
            model_name="inscricaoevento",
            name="metodo_pagamento",
            field=models.CharField(
                blank=True,
                choices=[("pix", "Pix"), ("boleto", "Boleto"), ("faturar", "Faturar")],
                max_length=20,
                null=True,
            ),
        ),
    ]
