# Generated by Django 5.2.5 on 2025-11-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0028_update_metodo_pagamento_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricaoevento",
            name="pagamento_validado",
            field=models.BooleanField(
                default=False, help_text="Indica se o pagamento informado foi validado pela equipe."
            ),
        ),
    ]
