# Generated by Django 5.2.5 on 2025-11-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0030_eventomidia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="valor",
        ),
        migrations.AddField(
            model_name="evento",
            name="valor_associado",
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text="Valor aplicado para associados.", max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="valor_nucleado",
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text="Valor aplicado para nucleados.", max_digits=8, null=True
            ),
        ),
    ]
