# Generated by Django 5.2.5 on 2025-11-21 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0031_remove_evento_valor_evento_valor_associado_and_more"),
        ("pagamentos", "0003_pedido_documento_pedido_email_pedido_nome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricaoevento",
            name="transacao",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inscricao_evento",
                to="pagamentos.transacao",
            ),
        ),
    ]
