# Generated by Django 5.2.5 on 2025-12-06 00:02

import django.db.models.deletion
import django.utils.timezone
import eventos.validators
from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0032_inscricaoevento_transacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscricaoevento",
            name="metodo_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pix", "Pix"),
                    ("boleto", "Boleto"),
                    ("card", "Cartão de crédito"),
                    ("faturar_avista", "Faturar à vista"),
                    ("faturar_2x", "Faturar em 2x"),
                    ("faturar_3x", "Faturar em 3x"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Convite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("publico_alvo", models.CharField(max_length=100)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("local", models.CharField(max_length=255)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                ("cronograma", models.TextField(blank=True)),
                ("informacoes_adicionais", models.TextField(blank=True)),
                (
                    "numero_participantes",
                    models.PositiveIntegerField(
                        blank=True, null=True, validators=[MinValueValidator(1)]
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="eventos/convites/",
                        validators=[eventos.validators.validate_uploaded_file],
                    ),
                ),
                ("short_code", models.CharField(editable=False, max_length=16, unique=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="convites", to="eventos.evento"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
