# Generated by Django 5.2.5 on 2025-12-11 15:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0033_alter_inscricaoevento_metodo_pagamento_convite"),
        ("tokens", "0020_totpdevice_base32_secrets"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreRegistroConvite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                ("codigo", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("pendente", "Pendente"), ("enviado", "Enviado")], default="pendente", max_length=20
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pre_registros", to="eventos.evento"
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_registros_convite",
                        to="tokens.tokenacesso",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("email", "evento")},
            },
        ),
    ]
