# Generated by Django 5.2.5 on 2025-12-16 21:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0034_preregistroconvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricaoevento",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
