# Generated by Django 5.2.5 on 2026-01-29 17:31

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import eventos.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0036_inscricaoevento_condicao_faturamento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BriefingTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=150)),
                ("descricao", models.TextField(blank=True)),
                ("estrutura", models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Template de Briefing",
                "verbose_name_plural": "Templates de Briefing",
                "ordering": ["nome"],
            },
        ),
        migrations.RemoveField(
            model_name="evento",
            name="briefing",
        ),
        migrations.CreateModel(
            name="BriefingEvento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "respostas",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("orcamentado", "Orçamentado"),
                            ("aprovado", "Aprovado"),
                            ("recusado", "Recusado"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                (
                    "versao_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="eventos/briefings/",
                        validators=[eventos.validators.validate_uploaded_file],
                    ),
                ),
                ("orcamento_enviado_em", models.DateTimeField(blank=True, null=True)),
                ("aprovado_em", models.DateTimeField(blank=True, null=True)),
                ("recusado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="briefings_aprovados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="briefing", to="eventos.evento"
                    ),
                ),
                (
                    "orcamento_enviado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="briefings_orcamento_enviados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recusado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="briefings_recusados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="briefings",
                        to="eventos.briefingtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Briefing de Evento",
                "verbose_name_plural": "Briefings de Eventos",
            },
        ),
    ]
