# Generated by Django 5.2.5 on 2026-03-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0037_briefingtemplate_remove_evento_briefing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="cover_focal_preset",
            field=models.CharField(
                blank=True,
                choices=[("top", "Topo"), ("center", "Centro"), ("bottom", "Base")],
                default="",
                help_text="Define o enquadramento vertical da imagem de capa no hero.",
                max_length=12,
            ),
        ),
    ]
