# Generated by Django 5.2.2 on 2025-06-11 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_conexoes", models.BooleanField(default=True)),
                ("email_mensagens", models.BooleanField(default=True)),
                ("email_eventos", models.BooleanField(default=True)),
                ("email_newsletter", models.BooleanField(default=True)),
                ("sistema_conexoes", models.BooleanField(default=True)),
                ("sistema_mensagens", models.BooleanField(default=True)),
                ("sistema_eventos", models.BooleanField(default=True)),
                ("sistema_comentarios", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Notificação",
                "verbose_name_plural": "Configurações de Notificação",
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("bio", models.TextField(blank=True)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("genero", models.CharField(blank=True, max_length=1)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("endereco", models.CharField(blank=True, max_length=255)),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(blank=True, max_length=2)),
                ("cep", models.CharField(blank=True, max_length=10)),
                ("facebook", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("idioma", models.CharField(blank=True, max_length=10)),
                ("fuso_horario", models.CharField(blank=True, max_length=50)),
                ("perfil_publico", models.BooleanField(default=True)),
                ("mostrar_email", models.BooleanField(default=True)),
                ("mostrar_telefone", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil",
                "verbose_name_plural": "Perfis",
            },
        ),
    ]
