# Generated by Django 5.2.2 on 2025-06-11 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Perfil",
        ),
    ]
