# Generated by Django 5.2.5 on 2025-11-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamentos", "0002_transacao_metodo_external_id_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="documento",
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name="Documento"),
        ),
        migrations.AddField(
            model_name="pedido",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="E-mail do cliente"),
        ),
        migrations.AddField(
            model_name="pedido",
            name="nome",
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name="Nome do cliente"),
        ),
        migrations.AddField(
            model_name="transacao",
            name="detalhes",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="Detalhes da transação"),
        ),
        migrations.AlterField(
            model_name="transacao",
            name="external_id",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Identificador externo"),
        ),
        migrations.AlterField(
            model_name="transacao",
            name="metodo",
            field=models.CharField(
                choices=[("pix", "Pix"), ("card", "Cartão de crédito"), ("boleto", "Boleto bancário")],
                max_length=20,
                verbose_name="Método",
            ),
        ),
    ]
