# Generated by Django 5.2.5 on 2025-11-24 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0016_organizacao_mercado_pago_access_token_and_more"),
        ("pagamentos", "0003_pedido_documento_pedido_email_pedido_nome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="organizacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pedidos",
                to="organizacoes.organizacao",
                verbose_name="Organização",
            ),
        ),
        migrations.AlterField(
            model_name="transacao",
            name="metodo",
            field=models.CharField(
                choices=[
                    ("pix", "Pix"),
                    ("card", "Cartão de crédito"),
                    ("boleto", "Boleto bancário"),
                    ("paypal", "PayPal"),
                ],
                max_length=20,
                verbose_name="Método",
            ),
        ),
    ]
