# Generated by Django 5.2.2 on 2025-08-07 19:04

import datetime
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoConta",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("receber_notificacoes_email", models.BooleanField(default=True)),
                (
                    "frequencia_notificacoes_email",
                    models.CharField(
                        choices=[("imediata", "Imediata"), ("diaria", "Diária"), ("semanal", "Semanal")],
                        default="imediata",
                        max_length=8,
                    ),
                ),
                ("receber_notificacoes_whatsapp", models.BooleanField(default=False)),
                (
                    "frequencia_notificacoes_whatsapp",
                    models.CharField(
                        choices=[("imediata", "Imediata"), ("diaria", "Diária"), ("semanal", "Semanal")],
                        default="imediata",
                        max_length=8,
                    ),
                ),
                ("receber_notificacoes_push", models.BooleanField(default=True)),
                (
                    "frequencia_notificacoes_push",
                    models.CharField(
                        choices=[("imediata", "Imediata"), ("diaria", "Diária"), ("semanal", "Semanal")],
                        default="imediata",
                        max_length=8,
                    ),
                ),
                (
                    "idioma",
                    models.CharField(
                        choices=[("pt-BR", "Português"), ("en-US", "English"), ("es-ES", "Español")],
                        default="pt-BR",
                        max_length=5,
                    ),
                ),
                (
                    "tema",
                    models.CharField(
                        choices=[("claro", "Claro"), ("escuro", "Escuro"), ("automatico", "Automático")],
                        default="claro",
                        max_length=10,
                    ),
                ),
                (
                    "hora_notificacao_diaria",
                    models.TimeField(
                        default=datetime.time(8, 0), help_text="Horário para envio de notificações diárias"
                    ),
                ),
                (
                    "hora_notificacao_semanal",
                    models.TimeField(
                        default=datetime.time(8, 0), help_text="Horário para envio de notificações semanais"
                    ),
                ),
                (
                    "dia_semana_notificacao",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Segunda"),
                            (1, "Terça"),
                            (2, "Quarta"),
                            (3, "Quinta"),
                            (4, "Sexta"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        default=0,
                        help_text="Dia da semana para notificações semanais",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-modified"],
                "constraints": [models.UniqueConstraint(fields=("user",), name="configuracao_conta_user_unique")],
            },
        ),
    ]
