# Generated by Django 5.2.2 on 2025-07-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0001_update_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaoconta",
            name="frequencia_notificacoes_email",
            field=models.CharField(
                choices=[("imediata", "Imediata"), ("diaria", "Diária"), ("semanal", "Semanal")],
                default="imediata",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="configuracaoconta",
            name="frequencia_notificacoes_whatsapp",
            field=models.CharField(
                choices=[("imediata", "Imediata"), ("diaria", "Diária"), ("semanal", "Semanal")],
                default="imediata",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="configuracaoconta",
            name="idioma",
            field=models.CharField(
                choices=[("pt-BR", "Português"), ("en-US", "English"), ("es-ES", "Español")],
                default="pt-BR",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="configuracaoconta",
            name="tema",
            field=models.CharField(
                choices=[("claro", "Claro"), ("escuro", "Escuro"), ("automatico", "Automático")],
                default="claro",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="configuracaoconta",
            name="tema_escuro",
            field=models.BooleanField(default=False, help_text="Obsoleto; use 'tema'"),
        ),
    ]
