# Generated by Django 5.2.2 on 2025-08-08 12:47

import core.fields
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoContaLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("campo", models.CharField(max_length=50)),
                ("valor_antigo", models.TextField(blank=True, null=True)),
                ("valor_novo", models.TextField(blank=True, null=True)),
                ("ip", core.fields.EncryptedCharField(blank=True, max_length=45, null=True)),
                ("user_agent", core.fields.EncryptedCharField(blank=True, max_length=512, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoContextual",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "escopo_tipo",
                    models.CharField(
                        choices=[("organizacao", "Organização"), ("nucleo", "Núcleo"), ("evento", "Evento")],
                        max_length=20,
                    ),
                ),
                ("escopo_id", models.UUIDField()),
                (
                    "frequencia_notificacoes_email",
                    models.CharField(
                        choices=[("imediata", "Imediata"), ("diaria", "Diária"), ("semanal", "Semanal")],
                        default="imediata",
                        max_length=8,
                    ),
                ),
                (
                    "frequencia_notificacoes_whatsapp",
                    models.CharField(
                        choices=[("imediata", "Imediata"), ("diaria", "Diária"), ("semanal", "Semanal")],
                        default="imediata",
                        max_length=8,
                    ),
                ),
                ("idioma", models.CharField(default="pt-BR", max_length=5)),
                (
                    "tema",
                    models.CharField(
                        choices=[("claro", "Claro"), ("escuro", "Escuro"), ("automatico", "Automático")],
                        default="claro",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracoes_contextuais",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-modified"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "escopo_tipo", "escopo_id"), name="config_contextual_user_scope_unique"
                    )
                ],
            },
        ),
    ]
