# Generated by Django 5.2.2 on 2025-08-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0002_configuracaocontalog_configuracaocontextual"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuracaocontalog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="configuracaocontalog",
            old_name="created",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="configuracaocontalog",
            name="fonte",
            field=models.CharField(
                choices=[("UI", "UI"), ("API", "API"), ("import", "import")], default="UI", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="configuracaocontextual",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="configuracaocontextual",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
