# Generated by Django 5.2.2 on 2025-08-01 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0002_configuracaoconta_frequencia_notificacoes_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="configuracaoconta",
            constraint=models.UniqueConstraint(fields=("user",), name="configuracao_conta_user_unique"),
        ),
    ]
