# Generated by Django 5.2.5 on 2025-08-14 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0003_configuracao_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaoconta",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name="configuracaoconta",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="configuracaocontextual",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name="configuracaocontextual",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
