# Generated by Django 5.2.2 on 2025-08-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0003_configuracaoconta_configuracao_conta_user_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaoconta",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
