# Generated by Django 5.2.5 on 2025-08-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0004_alter_configuracaoconta_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaocontextual",
            name="frequencia_notificacoes_push",
            field=models.CharField(
                choices=[("imediata", "Imediata"), ("diaria", "Diária"), ("semanal", "Semanal")],
                default="imediata",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="configuracaocontextual",
            name="receber_notificacoes_push",
            field=models.BooleanField(default=True),
        ),
    ]
