# Generated by Django 5.2.5 on 2025-08-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0005_configuracaocontextual_frequencia_notificacoes_push_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaocontextual",
            name="receber_notificacoes_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="configuracaocontextual",
            name="receber_notificacoes_whatsapp",
            field=models.BooleanField(default=False),
        ),
    ]
