
# Generated by Django 5.2.5 on 2025-08-20 18:13


from django.db import migrations, models



def copy_preferences(apps, schema_editor):
    ConfiguracaoContextual = apps.get_model("configuracoes", "ConfiguracaoContextual")
    ConfiguracaoConta = apps.get_model("configuracoes", "ConfiguracaoConta")
    for ctx in ConfiguracaoContextual.objects.all():
        try:
            conta = ConfiguracaoConta.objects.get(user_id=ctx.user_id)
            ctx.receber_notificacoes_email = conta.receber_notificacoes_email
            ctx.receber_notificacoes_whatsapp = conta.receber_notificacoes_whatsapp
            ctx.save(update_fields=["receber_notificacoes_email", "receber_notificacoes_whatsapp"])
        except ConfiguracaoConta.DoesNotExist:
            # In case there is no global config, keep defaults
            pass



class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0005_configuracaocontextual_frequencia_notificacoes_push_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaocontextual",
            name="receber_notificacoes_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="configuracaocontextual",
            name="receber_notificacoes_whatsapp",
            field=models.BooleanField(default=False),
        ),

        migrations.RunPython(copy_preferences, migrations.RunPython.noop),

    ]
