# Generated by Django 5.2.2 on 2025-08-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0006_remove_tema_escuro_add_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaoconta",
            name="dia_semana_notificacao",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Segunda"),
                    (1, "Terça"),
                    (2, "Quarta"),
                    (3, "Quinta"),
                    (4, "Sexta"),
                    (5, "Sábado"),
                    (6, "Domingo"),
                ],
                default=0,
                help_text="Dia da semana para notificações semanais",
            ),
        ),
    ]
