# Generated by Django 5.2.5 on 2025-08-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0006_configuracaocontextual_receber_notificacoes_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaocontextual",
            name="frequencia_notificacoes_email",
            field=models.CharField(
                blank=True,
                choices=[("imediata", "Imediata"), ("diaria", "Diária"), ("semanal", "Semanal")],
                default=None,
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="configuracaocontextual",
            name="frequencia_notificacoes_push",
            field=models.CharField(
                blank=True,
                choices=[("imediata", "Imediata"), ("diaria", "Diária"), ("semanal", "Semanal")],
                default=None,
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="configuracaocontextual",
            name="frequencia_notificacoes_whatsapp",
            field=models.CharField(
                blank=True,
                choices=[("imediata", "Imediata"), ("diaria", "Diária"), ("semanal", "Semanal")],
                default=None,
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="configuracaocontextual",
            name="idioma",
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="configuracaocontextual",
            name="receber_notificacoes_email",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="configuracaocontextual",
            name="receber_notificacoes_push",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="configuracaocontextual",
            name="receber_notificacoes_whatsapp",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="configuracaocontextual",
            name="tema",
            field=models.CharField(
                blank=True,
                choices=[("claro", "Claro"), ("escuro", "Escuro"), ("automatico", "Automático")],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
