# Generated by Django 5.2.5 on 2025-08-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0007_alter_configuracaocontextual_frequencia_notificacoes_email_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="configuracaocontextual",
            name="config_contextual_user_scope_unique",
        ),
        migrations.DeleteModel(
            name="ConfiguracaoContextual",
        ),
    ]
