# Generated by Django 5.2.2 on 2025-08-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0007_alter_configuracaoconta_dia_semana_notificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaoconta",
            name="frequencia_notificacoes_push",
            field=models.CharField(
                choices=[("imediata", "Imediata"), ("diaria", "Diária"), ("semanal", "Semanal")],
                default="imediata",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="configuracaoconta",
            name="receber_notificacoes_push",
            field=models.BooleanField(default=True),
        ),
    ]
