# Generated by Django 5.2.5 on 2025-09-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0008_delete_configuracaocontextual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaoconta",
            name="tema",
            field=models.CharField(choices=[("claro", "Claro"), ("escuro", "Escuro")], default="claro", max_length=10),
        ),
    ]
