# Generated by Django 5.2.5 on 2025-11-19 20:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0009_alter_configuracaoconta_tema"),
        ("organizacoes", "0014_organizacaofeedsync"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaoconta",
            name="chat_habilitado",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ConfiguracaoChatOrganizacao",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("chat_habilitado", models.BooleanField(default=True)),
                (
                    "organizacao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracao_chat",
                        to="organizacoes.organizacao",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
