# Generated by Django 5.2.5 on 2026-02-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0010_configuracaoconta_chat_habilitado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaoconta",
            name="idioma",
            field=models.CharField(
                choices=[("pt-br", "Português (Brasil)"), ("en", "English"), ("es", "Español")],
                default="pt-br",
                max_length=5,
            ),
        ),
    ]
