# Generated by Django 5.2.5 on 2026-02-09 20:32

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0012_normalize_configuracaoconta_idioma_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaocontalog",
            name="ip",
            field=core.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="configuracaocontalog",
            name="user_agent",
            field=core.fields.EncryptedCharField(blank=True, max_length=2048, null=True),
        ),
    ]
