# Generated by Django 5.2.2 on 2025-07-19 17:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nucleos", "0001_initial"),
        ("organizacoes", "0002_alter_organizacao_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParceriaEvento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contato_adicional_nome", models.CharField(blank=True, max_length=150)),
                ("contato_adicional_cpf", models.CharField(blank=True, max_length=14)),
                ("whatsapp_contato", models.CharField(max_length=15)),
                (
                    "tipo_parceria",
                    models.CharField(
                        choices=[
                            ("patrocinio", "Patrocínio"),
                            ("mentoria", "Mentoria"),
                            ("mantenedor", "Mantenedor"),
                            ("outro", "Outro"),
                        ],
                        default="patrocinio",
                        max_length=20,
                    ),
                ),
                ("acordo", models.FileField(blank=True, null=True, upload_to="parcerias/contratos/")),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Parceria de Evento",
                "verbose_name_plural": "Parcerias de Eventos",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
                ("endereco", models.CharField(max_length=255)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                ("cep", models.CharField(max_length=9)),
                (
                    "status",
                    models.PositiveSmallIntegerField(choices=[(0, "Ativo"), (1, "Concluído"), (2, "Cancelado")]),
                ),
                (
                    "publico_alvo",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Público"), (1, "Somente nucleados"), (2, "Apenas associados")]
                    ),
                ),
                ("numero_convidados", models.PositiveIntegerField()),
                ("numero_presentes", models.PositiveIntegerField()),
                ("valor_ingresso", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("orcamento", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("cronograma", models.TextField(blank=True)),
                ("informacoes_adicionais", models.TextField(blank=True)),
                ("contato_nome", models.CharField(max_length=100)),
                ("contato_email", models.EmailField(blank=True, max_length=254)),
                ("contato_whatsapp", models.CharField(blank=True, max_length=15)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="eventos/avatars/")),
                ("cover", models.ImageField(blank=True, null=True, upload_to="eventos/capas/")),
                ("briefing", models.TextField(blank=True, null=True)),
                (
                    "coordenador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nucleo",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nucleos.nucleo"
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizacoes.organizacao"),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
        migrations.CreateModel(
            name="BriefingEvento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("objetivos", models.TextField()),
                ("publico_alvo", models.TextField()),
                ("requisitos_tecnicos", models.TextField()),
                ("cronograma_resumido", models.TextField(blank=True)),
                ("conteudo_programatico", models.TextField(blank=True)),
                ("observacoes", models.TextField(blank=True)),
                ("evento", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="agenda.evento")),
            ],
            options={
                "verbose_name": "Briefing de Evento",
                "ordering": ["evento"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackNota",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "nota",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comentario", models.TextField(blank=True)),
                ("data_feedback", models.DateTimeField(auto_now_add=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="feedbacks", to="agenda.evento"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Feedback de Nota",
                "verbose_name_plural": "Feedbacks de Notas",
            },
        ),
        migrations.CreateModel(
            name="InscricaoEvento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data_inscricao", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pendente", "Pendente"), ("confirmada", "Confirmada"), ("cancelada", "Cancelada")],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("presente", models.BooleanField(default=False)),
                (
                    "avaliacao",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("valor_pago", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                (
                    "metodo_pagamento",
                    models.CharField(
                        blank=True,
                        choices=[("pix", "Pix"), ("boleto", "Boleto"), ("gratuito", "Gratuito"), ("outro", "Outro")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("comprovante_pagamento", models.FileField(blank=True, null=True, upload_to="eventos/comprovantes/")),
                ("observacao", models.TextField(blank=True)),
                ("data_confirmacao", models.DateTimeField(blank=True, null=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="inscricoes", to="agenda.evento"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscricoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaterialDivulgacaoEvento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("banner", "Banner"), ("flyer", "Flyer"), ("video", "Vídeo"), ("outro", "Outro")],
                        max_length=20,
                    ),
                ),
                ("arquivo", models.FileField(upload_to="eventos/divulgacao/")),
                ("imagem_thumb", models.ImageField(blank=True, null=True, upload_to="eventos/divulgacao/thumbs/")),
                ("data_publicacao", models.DateField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
                ("tags", models.CharField(blank=True, max_length=255)),
                ("evento", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="agenda.evento")),
            ],
            options={
                "verbose_name": "Material de Divulgação de Evento",
                "verbose_name_plural": "Materiais de Divulgação de Eventos",
            },
        ),
    ]
