# Generated by Django 5.2.2 on 2025-07-19 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0001_initial"),
        ("empresas", "0001_initial"),
        ("nucleos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parceriaevento",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="parcerias", to="empresas.empresa"
            ),
        ),
        migrations.AddField(
            model_name="parceriaevento",
            name="evento",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="agenda.evento"),
        ),
        migrations.AddField(
            model_name="parceriaevento",
            name="nucleo",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nucleos.nucleo"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feedbacknota",
            unique_together={("usuario", "evento")},
        ),
        migrations.AlterUniqueTogether(
            name="inscricaoevento",
            unique_together={("user", "evento")},
        ),
    ]
