# Generated by Django 5.2.2 on 2025-07-21 18:21

from django.db import migrations


def copy_data_inscricao(apps, schema_editor):
    Inscricao = apps.get_model("agenda", "InscricaoEvento")
    for insc in Inscricao.objects.all().only("id", "data_inscricao", "created_at"):
        if insc.data_inscricao:
            Inscricao.objects.filter(pk=insc.pk).update(created_at=insc.data_inscricao)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(copy_data_inscricao, noop),
        migrations.RemoveField(
            model_name="inscricaoevento",
            name="data_inscricao",
        ),
    ]
