# Generated by Django 5.2.2 on 2025-07-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0003_migrate_data_inscricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="espera_habilitada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evento",
            name="orcamento_estimado",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="participantes_maximo",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="valor_gasto",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="inscricaoevento",
            name="check_in_realizado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inscricaoevento",
            name="qrcode_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
