# Generated by Django 5.2.2 on 2025-07-26 18:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0004_evento_espera_habilitada_evento_orcamento_estimado_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="briefingevento",
            name="avaliado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="briefingevento",
            name="avaliado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="briefings_avaliados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="briefingevento",
            name="status",
            field=models.CharField(
                choices=[("criado", "Criado"), ("aprovado", "Aprovado"), ("devolvido", "Devolvido")],
                default="criado",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="inscricaoevento",
            name="posicao_espera",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="materialdivulgacaoevento",
            name="avaliado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="materialdivulgacaoevento",
            name="avaliado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materiais_avaliados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="materialdivulgacaoevento",
            name="status",
            field=models.CharField(
                choices=[("criado", "Criado"), ("aprovado", "Aprovado"), ("devolvido", "Devolvido")],
                default="criado",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="parceriaevento",
            name="avaliacao",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="parceriaevento",
            name="comentario",
            field=models.TextField(blank=True),
        ),
    ]
