# Generated by Django 5.2.2 on 2025-08-01 00:48

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0005_briefingevento_avaliado_em_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evento",
            old_name="endereco",
            new_name="local",
        ),
        migrations.AlterField(
            model_name="evento",
            name="id",
            field=models.UUIDField(
                primary_key=True, default=uuid.uuid4, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="cidade",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        r"^[A-Za-zÀ-ÿ\s-]+$", "Cidade inválida"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="estado",
            field=models.CharField(
                max_length=2,
                validators=[
                    django.core.validators.RegexValidator(
                        r"^[A-Z]{2}$", "UF inválida"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="cep",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        r"^\d{5}-\d{3}$", "CEP inválido"
                    )
                ],
            ),
        ),
        migrations.RemoveField(
            model_name="parceriaevento",
            name="contato_adicional_nome",
        ),
        migrations.RemoveField(
            model_name="parceriaevento",
            name="contato_adicional_cpf",
        ),
        migrations.RemoveField(
            model_name="parceriaevento",
            name="whatsapp_contato",
        ),
        migrations.AddField(
            model_name="parceriaevento",
            name="cnpj",
            field=models.CharField(
                default="00000000000000",
                max_length=14,
                validators=[
                    django.core.validators.RegexValidator(
                        r"^\d{14}$", "CNPJ inválido"
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parceriaevento",
            name="contato",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parceriaevento",
            name="representante_legal",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="briefingevento",
            name="status",
            field=models.CharField(
                default="rascunho",
                max_length=15,
                choices=[
                    ("rascunho", "Rascunho"),
                    ("orcamentado", "Orçamentado"),
                    ("aprovado", "Aprovado"),
                    ("recusado", "Recusado"),
                ],
            ),
        ),
        migrations.AddField(
            model_name="briefingevento",
            name="orcamento_enviado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="briefingevento",
            name="aprovado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="briefingevento",
            name="recusado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="briefingevento",
            name="motivo_recusa",
            field=models.TextField(blank=True),
        ),
    ]
