# Generated by Django 5.2.5 on 2025-09-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0006_evento_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="eventos/avatars/"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="eventos/covers/"),
        ),
    ]
