# Generated by Django 5.2.2 on 2025-08-01 00:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0006_evento_uuid_local"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
