# Generated by Django 5.2.2 on 2025-08-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0007_alter_evento_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialdivulgacaoevento",
            name="ativo",
        ),
        migrations.AddField(
            model_name="materialdivulgacaoevento",
            name="motivo_devolucao",
            field=models.TextField(blank=True),
        ),
    ]
