# Generated by Django 5.2.2 on 2025-08-04 14:58

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models
from django.db.models import F


def copy_timestamps(apps, schema_editor):
    Evento = apps.get_model("agenda", "Evento")
    InscricaoEvento = apps.get_model("agenda", "InscricaoEvento")
    Evento.objects.update(created=F("created_at"), modified=F("updated_at"))
    InscricaoEvento.objects.update(created=F("created_at"), modified=F("updated_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0008_remove_materialdivulgacaoevento_ativo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="briefingevento",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="created"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="briefingevento",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AddField(
            model_name="evento",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="created"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evento",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AddField(
            model_name="evento",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evento",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inscricaoevento",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="created"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inscricaoevento",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AddField(
            model_name="inscricaoevento",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inscricaoevento",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parceriaevento",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="created"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parceriaevento",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AddField(
            model_name="materialdivulgacaoevento",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="created"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="materialdivulgacaoevento",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AddField(
            model_name="feedbacknota",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="created"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedbacknota",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.RunPython(copy_timestamps, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="evento",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="inscricaoevento",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="inscricaoevento",
            name="updated_at",
        ),
    ]
