# Generated by Django 5.2.2 on 2025-08-04 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0010_briefingevento_deleted_briefingevento_deleted_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalInscricaoEvento",
        ),
    ]
