# Generated by Django 5.2.2 on 2025-08-05 00:46

from django.db import migrations


def migrate_avaliacao_to_feedback(apps, schema_editor):
    InscricaoEvento = apps.get_model("agenda", "InscricaoEvento")
    FeedbackNota = apps.get_model("agenda", "FeedbackNota")
    for inscricao in InscricaoEvento.objects.exclude(avaliacao__isnull=True):
        FeedbackNota.objects.update_or_create(
            evento_id=inscricao.evento_id,
            usuario_id=inscricao.user_id,
            defaults={"nota": inscricao.avaliacao, "comentario": ""},
        )


def reverse_migrate_avaliacao(apps, schema_editor):
    InscricaoEvento = apps.get_model("agenda", "InscricaoEvento")
    FeedbackNota = apps.get_model("agenda", "FeedbackNota")
    for fb in FeedbackNota.objects.all():
        InscricaoEvento.objects.filter(
            evento_id=fb.evento_id, user_id=fb.usuario_id
        ).update(avaliacao=fb.nota)


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0011_delete_historicalinscricaoevento"),
    ]

    operations = [
        migrations.RunPython(
            migrate_avaliacao_to_feedback, reverse_migrate_avaliacao
        ),
        migrations.RemoveField(
            model_name="inscricaoevento",
            name="avaliacao",
        ),
    ]
