# Generated by Django 5.2.2 on 2025-08-05 13:10

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0014_alter_eventolog_created_alter_eventolog_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventolog",
            name="detalhes",
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
