# Generated by Django 5.2.2 on 2025-08-06 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0015_alter_eventolog_detalhes"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricaoevento",
            name="avaliacao",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="inscricaoevento",
            name="feedback",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: None,
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]
