# Generated by Django 5.2.2 on 2025-08-07 18:25

import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0018_tarefa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmaterialdivulgacaoevento",
            name="avaliado_por",
        ),
        migrations.RemoveField(
            model_name="historicalmaterialdivulgacaoevento",
            name="evento",
        ),
        migrations.RemoveField(
            model_name="historicalmaterialdivulgacaoevento",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalparceriaevento",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="historicalparceriaevento",
            name="evento",
        ),
        migrations.RemoveField(
            model_name="historicalparceriaevento",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalparceriaevento",
            name="nucleo",
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="tarefalog",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="tarefalog",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.DeleteModel(
            name="HistoricalBriefingEvento",
        ),
        migrations.DeleteModel(
            name="HistoricalMaterialDivulgacaoEvento",
        ),
        migrations.DeleteModel(
            name="HistoricalParceriaEvento",
        ),
    ]
