# Generated by Django 5.2.2 on 2025-08-07 19:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizacoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Nucleo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("nome", models.CharField(max_length=255)),
                ("slug", models.SlugField(default=uuid.uuid4, max_length=255, unique=True)),
                ("descricao", models.TextField(blank=True)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="nucleos/avatars/")),
                ("cover", models.ImageField(blank=True, null=True, upload_to="nucleos/capas/")),
                ("inativa", models.BooleanField(default=False)),
                ("inativada_em", models.DateTimeField(blank=True, null=True)),
                ("mensalidade", models.DecimalField(decimal_places=2, default=Decimal("30.00"), max_digits=8)),
                (
                    "organizacao",
                    models.ForeignKey(
                        db_column="organizacao",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nucleos",
                        to="organizacoes.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Núcleo",
                "verbose_name_plural": "Núcleos",
            },
        ),
        migrations.CreateModel(
            name="CoordenadorSuplente",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("inicio", models.DateTimeField()),
                ("fim", models.DateTimeField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suplencias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nucleo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordenadores_suplentes",
                        to="nucleos.nucleo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coordenador Suplente",
                "verbose_name_plural": "Coordenadores Suplentes",
            },
        ),
        migrations.CreateModel(
            name="ConviteNucleo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "papel",
                    models.CharField(choices=[("membro", "Membro"), ("coordenador", "Coordenador")], max_length=20),
                ),
                ("usado_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("nucleo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="nucleos.nucleo")),
            ],
            options={
                "verbose_name": "Convite para Núcleo",
                "verbose_name_plural": "Convites para Núcleos",
            },
        ),
        migrations.CreateModel(
            name="ParticipacaoNucleo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_coordenador", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("pendente", "Pendente"), ("aprovado", "Aprovado"), ("recusado", "Recusado")],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("data_solicitacao", models.DateTimeField(auto_now_add=True)),
                ("data_decisao", models.DateTimeField(blank=True, null=True)),
                ("justificativa", models.TextField(blank=True)),
                (
                    "decidido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisoes_participacao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nucleo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="participacoes", to="nucleos.nucleo"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Participação no Núcleo",
                "verbose_name_plural": "Participações nos Núcleos",
                "unique_together": {("user", "nucleo")},
            },
        ),
    ]
