# Generated by Django 5.2.2 on 2025-06-20 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizacoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Nucleo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="nucleos/avatars/"
                    ),
                ),
                ("data_criacao", models.DateField(auto_now_add=True)),
                (
                    "membros",
                    models.ManyToManyField(
                        blank=True, related_name="nucleos", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nucleos",
                        to="organizacoes.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Núcleo",
                "verbose_name_plural": "Núcleos",
            },
        ),
    ]
