# Generated by Django 5.2.4 on 2025-07-15 19:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizacoes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nucleo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="nucleos/avatars/")),
                ("data_criacao", models.DateField(auto_now_add=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        db_column="organizacao",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nucleos",
                        to="organizacoes.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Núcleo",
                "verbose_name_plural": "Núcleos",
            },
        ),
    ]
