# Generated by Django 5.2.4 on 2025-07-15 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nucleo",
            name="membros",
            field=models.ManyToManyField(blank=True, related_name="nucleos", to=settings.AUTH_USER_MODEL),
        ),
    ]
