# Generated by Django 5.2.2 on 2025-07-25 19:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nucleo",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nucleo",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="participacaonucleo",
            name="data_decisao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="participacaonucleo",
            name="data_solicitacao",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participacaonucleo",
            name="decidido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decisoes_participacao",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="participacaonucleo",
            name="status",
            field=models.CharField(
                choices=[("pendente", "Pendente"), ("aprovado", "Aprovado"), ("recusado", "Recusado")],
                default="pendente",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="CoordenadorSuplente",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("periodo_inicio", models.DateTimeField()),
                ("periodo_fim", models.DateTimeField()),
                (
                    "nucleo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordenadores_suplentes",
                        to="nucleos.nucleo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suplencias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coordenador Suplente",
                "verbose_name_plural": "Coordenadores Suplentes",
            },
        ),
    ]
