# Generated by Django 5.2.2 on 2025-08-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "0002_coordenadorsuplente_periodo_softdelete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordenadorsuplente",
            name="periodo_fim",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="coordenadorsuplente",
            name="periodo_inicio",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="participacaonucleo",
            name="status",
            field=models.CharField(
                choices=[("pendente", "Pendente"), ("aprovado", "Aprovado"), ("recusado", "Recusado")],
                db_index=True,
                default="pendente",
                max_length=10,
            ),
        ),
    ]
