# Generated by Django 5.2.2 on 2025-07-31 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "0002_nucleo_deleted_nucleo_deleted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nucleo",
            name="membros",
            field=models.ManyToManyField(
                related_name="nucleos",
                through="nucleos.ParticipacaoNucleo",
                through_fields=("nucleo", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
