# Generated by Django 5.2.5 on 2025-08-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "0003_convite_tokens_suspensao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participacaonucleo",
            name="papel",
            field=models.CharField(
                choices=[("membro", "Membro"), ("coordenador", "Coordenador")], default="membro", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="participacaonucleo",
            name="status",
            field=models.CharField(
                choices=[("pendente", "Pendente"), ("ativo", "Ativo"), ("inativo", "Inativo")],
                db_index=True,
                default="pendente",
                max_length=20,
            ),
        ),
    ]
