# Generated by Django 5.2.5 on 2025-08-14 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "0004_alter_participacaonucleo_papel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="convitenucleo",
            name="criado_em",
        ),
        migrations.AddField(
            model_name="convitenucleo",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="convitenucleo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
