# Generated by Django 5.2.2 on 2025-08-04 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "0004_nucleo_slug_inativa"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coordenadorsuplente",
            old_name="periodo_fim",
            new_name="fim",
        ),
        migrations.RenameField(
            model_name="coordenadorsuplente",
            old_name="periodo_inicio",
            new_name="inicio",
        ),
        migrations.RemoveField(
            model_name="nucleo",
            name="data_criacao",
        ),
        migrations.RemoveField(
            model_name="nucleo",
            name="membros",
        ),
        migrations.AddField(
            model_name="coordenadorsuplente",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="coordenadorsuplente",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="participacaonucleo",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="participacaonucleo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
