# Generated by Django 5.2.5 on 2025-08-14 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "0005_remove_convitenucleo_criado_em_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nucleo",
            name="ativo",
        ),
    ]
