# Generated by Django 5.2.2 on 2025-08-04 23:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "0005_rename_periodo_fim_coordenadorsuplente_fim_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConviteNucleo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "papel",
                    models.CharField(choices=[("membro", "Membro"), ("coordenador", "Coordenador")], max_length=20),
                ),
                ("usado_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("nucleo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="nucleos.nucleo")),
            ],
            options={
                "verbose_name": "Convite para Núcleo",
                "verbose_name_plural": "Convites para Núcleos",
            },
        ),
    ]
