# Generated by Django 5.2.2 on 2025-08-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "0006_convitenucleo"),
    ]

    operations = [
        migrations.AddField(
            model_name="participacaonucleo",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="participacaonucleo",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="participacaonucleo",
            name="justificativa",
            field=models.TextField(blank=True),
        ),
    ]
