# Generated by Django 5.2.5 on 2025-08-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "0006_remove_nucleo_ativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="convitenucleo",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="convitenucleo",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
