# Generated by Django 5.2.5 on 2025-08-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "0007_convitenucleo_deleted_convitenucleo_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="nucleo",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
    ]
