# Generated by Django 5.2.5 on 2025-09-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "0009_nucleo_public_id"),
        ("organizacoes", "0008_alter_organizacaoatividadelog_detalhes"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="nucleo",
            name="uniq_org_slug",
        ),
        migrations.RemoveField(
            model_name="nucleo",
            name="slug",
        ),
        migrations.AddConstraint(
            model_name="nucleo",
            constraint=models.UniqueConstraint(fields=("organizacao", "nome"), name="uniq_org_nome"),
        ),
    ]
