# Generated by Django 5.2.5 on 2025-09-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "0010_remove_nucleo_uniq_org_slug_remove_nucleo_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nucleo",
            name="classificacao",
            field=models.CharField(
                choices=[
                    ("constituido", "Constituído"),
                    ("planejamento", "Planejamento"),
                    ("em_formacao", "Em formação"),
                ],
                default="planejamento",
                max_length=20,
                verbose_name="Classificação",
            ),
        ),
    ]
