# Generated by Django 5.2.5 on 2025-09-26 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "0011_nucleo_classificacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participacaonucleo",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="nucleo",
            name="consultor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nucleos_consultoria",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Consultor",
            ),
        ),
        migrations.AddField(
            model_name="participacaonucleo",
            name="papel_coordenador",
            field=models.CharField(
                blank=True,
                choices=[
                    ("coordenador_geral", "Coordenador Geral"),
                    ("vice_coordenador", "Vice coordenador"),
                    ("capacitacao", "Capacitação"),
                    ("marketing", "Marketing"),
                    ("eventos", "Eventos"),
                    ("financeiro", "Financeiro"),
                    ("relacoes_publicas", "Relações públicas"),
                    ("inovacao", "Inovação"),
                    ("valorizacao_empresaria", "Valorização empresária"),
                    ("gestao_excelencia", "Gestão e Excelência"),
                ],
                max_length=50,
                null=True,
                verbose_name="Papel de coordenação",
            ),
        ),
        migrations.AddConstraint(
            model_name="participacaonucleo",
            constraint=models.UniqueConstraint(fields=("user", "nucleo"), name="uniq_participacao_usuario_nucleo"),
        ),
        migrations.AddConstraint(
            model_name="participacaonucleo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("papel", "coordenador")),
                fields=("nucleo", "papel_coordenador"),
                name="uniq_coordenador_papel",
            ),
        ),
        migrations.AddConstraint(
            model_name="participacaonucleo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("papel", "coordenador"), ("papel_coordenador__isnull", False)),
                    models.Q(("papel", "membro"), ("papel_coordenador__isnull", True)),
                    _connector="OR",
                ),
                name="papel_coordenador_valido",
            ),
        ),
    ]
