# Generated by Django 5.2.5 on 2025-11-05 18:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_user_cpf_and_more"),
        ("nucleos", "0012_alter_participacaonucleo_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NucleoMidia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("file", models.FileField(upload_to="nucleos/portfolio/")),
                ("descricao", models.CharField(blank=True, max_length=255, verbose_name="Descrição")),
                (
                    "nucleo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="midias", to="nucleos.nucleo"
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, related_name="nucleo_midias", to="accounts.mediatag")),
            ],
            options={
                "verbose_name": "Mídia do Núcleo",
                "verbose_name_plural": "Portfólio do Núcleo",
            },
        ),
    ]
