# Generated by Django 5.2.5 on 2026-01-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "0013_nucleomidia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nucleo",
            name="mensalidade",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
