# Generated by Django 5.2.2 on 2025-08-07 19:04

import discussao.models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("nucleos", "0001_initial"),
        ("organizacoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="CategoriaDiscussao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("descricao", models.TextField(blank=True)),
                ("icone", models.ImageField(blank=True, null=True, upload_to="discussoes/icones/")),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias_discussao",
                        to="agenda.evento",
                    ),
                ),
                (
                    "nucleo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias_discussao",
                        to="nucleos.nucleo",
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias_discussao",
                        to="organizacoes.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Discussão",
                "verbose_name_plural": "Categorias de Discussão",
                "ordering": ["nome"],
                "unique_together": {("nome", "organizacao", "nucleo", "evento")},
            },
        ),
        migrations.CreateModel(
            name="DiscussionModerationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[("approve", "Aprovar"), ("reject", "Rejeitar"), ("remove", "Remover")], max_length=10
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussion_moderations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Moderação",
                "verbose_name_plural": "Logs de Moderação",
            },
        ),
        migrations.CreateModel(
            name="RespostaDiscussao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("conteudo", models.TextField()),
                ("arquivo", models.FileField(blank=True, null=True, upload_to="discussoes/arquivos/")),
                ("editado", models.BooleanField(default=False)),
                ("editado_em", models.DateTimeField(blank=True, null=True)),
                ("motivo_edicao", models.TextField(blank=True, default="")),
                ("search_vector", discussao.models.SearchVectorField(blank=True, editable=False, null=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas_discussao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas_filhas",
                        to="discussao.respostadiscussao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta de Discussão",
                "verbose_name_plural": "Respostas de Discussão",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="TopicoDiscussao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("conteudo", models.TextField()),
                (
                    "publico_alvo",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Todos"), (1, "Apenas nucleados"), (2, "Apenas associados")]
                    ),
                ),
                ("fechado", models.BooleanField(default=False)),
                ("resolvido", models.BooleanField(default=False)),
                ("numero_visualizacoes", models.PositiveIntegerField(default=0)),
                ("search_vector", discussao.models.SearchVectorField(blank=True, editable=False, null=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topicos_discussao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topicos",
                        to="discussao.categoriadiscussao",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="agenda.evento"
                    ),
                ),
                (
                    "melhor_resposta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="topico_melhor_resposta",
                        to="discussao.respostadiscussao",
                    ),
                ),
                (
                    "nucleo",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nucleos.nucleo"
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, related_name="topicos", to="discussao.tag")),
            ],
            options={
                "verbose_name": "Tópico de Discussão",
                "verbose_name_plural": "Tópicos de Discussão",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="respostadiscussao",
            name="topico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="respostas", to="discussao.topicodiscussao"
            ),
        ),
        migrations.CreateModel(
            name="Denuncia",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("object_id", models.PositiveIntegerField()),
                ("motivo", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pendente", "Pendente"), ("revisado", "Revisado"), ("rejeitado", "Rejeitado")],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="denuncias",
                        to="discussao.discussionmoderationlog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Denúncia",
                "verbose_name_plural": "Denúncias",
                "unique_together": {("user", "content_type", "object_id")},
            },
        ),
        migrations.CreateModel(
            name="InteracaoDiscussao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("valor", models.SmallIntegerField(choices=[(1, "Curtir"), (-1, "Não Curtir")], default=1)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "content_type", "object_id")},
            },
        ),
        migrations.AddIndex(
            model_name="topicodiscussao",
            index=models.Index(fields=["slug", "categoria"], name="discussao_t_slug_f19f97_idx"),
        ),
    ]
