# Generated by Django 5.2.2 on 2025-07-18 17:13

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("nucleos", "0001_initial"),
        ("organizacoes", "0002_alter_organizacao_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaDiscussao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("descricao", models.TextField(blank=True)),
                ("icone", models.ImageField(blank=True, null=True, upload_to="discussoes/icones/")),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="agenda.evento"
                    ),
                ),
                (
                    "nucleo",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nucleos.nucleo"
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizacoes.organizacao"),
                ),
            ],
            options={
                "unique_together": {("nome", "organizacao", "nucleo", "evento")},
            },
        ),
        migrations.CreateModel(
            name="TopicoDiscussao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("conteudo", models.TextField()),
                (
                    "publico_alvo",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Todos"), (1, "Apenas nucleados"), (2, "Apenas associados")]
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=255)),
                ("numero_visualizacoes", models.PositiveIntegerField(default=0)),
                ("fechado", models.BooleanField(default=False)),
                ("autor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "categoria",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="discussao.categoriadiscussao"),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="agenda.evento"
                    ),
                ),
                (
                    "nucleo",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nucleos.nucleo"
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="RespostaDiscussao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("conteudo", models.TextField()),
                ("arquivo", models.FileField(blank=True, null=True, upload_to="discussoes/arquivos/")),
                ("editado", models.BooleanField(default=False)),
                ("autor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="discussao.respostadiscussao",
                    ),
                ),
                (
                    "topico",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="discussao.topicodiscussao"),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="InteracaoDiscussao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("tipo", models.CharField(choices=[("like", "Like"), ("dislike", "Dislike")], max_length=10)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "content_type", "object_id")},
            },
        ),
        migrations.AddIndex(
            model_name="topicodiscussao",
            index=models.Index(fields=["slug", "categoria"], name="discussao_t_slug_f19f97_idx"),
        ),
    ]
