# Generated by Django 5.2.2 on 2025-07-18 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "__first__"),
        ("discussao", "0002_remove_forum_tables"),
        ("nucleos", "0001_initial"),
        ("organizacoes", "0002_alter_organizacao_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoriadiscussao",
            options={
                "ordering": ["nome"],
                "verbose_name": "Categoria de Discussão",
                "verbose_name_plural": "Categorias de Discussão",
            },
        ),
        migrations.AlterModelOptions(
            name="respostadiscussao",
            options={
                "ordering": ["created"],
                "verbose_name": "Resposta de Discussão",
                "verbose_name_plural": "Respostas de Discussão",
            },
        ),
        migrations.AlterModelOptions(
            name="topicodiscussao",
            options={
                "ordering": ["-created"],
                "verbose_name": "Tópico de Discussão",
                "verbose_name_plural": "Tópicos de Discussão",
            },
        ),
        migrations.RemoveField(
            model_name="interacaodiscussao",
            name="modified",
        ),
        migrations.AlterField(
            model_name="categoriadiscussao",
            name="evento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias_discussao",
                to="agenda.evento",
            ),
        ),
        migrations.AlterField(
            model_name="categoriadiscussao",
            name="nucleo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias_discussao",
                to="nucleos.nucleo",
            ),
        ),
        migrations.AlterField(
            model_name="categoriadiscussao",
            name="organizacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias_discussao",
                to="organizacoes.organizacao",
            ),
        ),
        migrations.AlterField(
            model_name="interacaodiscussao",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="interacaodiscussao",
            name="tipo",
            field=models.CharField(choices=[("like", "Curtir"), ("dislike", "Não Curtir")], max_length=7),
        ),
        migrations.AlterField(
            model_name="respostadiscussao",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respostas_discussao",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="respostadiscussao",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respostas_filhas",
                to="discussao.respostadiscussao",
            ),
        ),
        migrations.AlterField(
            model_name="respostadiscussao",
            name="topico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="respostas", to="discussao.topicodiscussao"
            ),
        ),
        migrations.AlterField(
            model_name="topicodiscussao",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topicos_discussao",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="topicodiscussao",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="topicos", to="discussao.categoriadiscussao"
            ),
        ),
    ]
