# Generated by Django 5.2.2 on 2025-07-25 22:28

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussao", "0003_alter_categoriadiscussao_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["nome"],
            },
        ),
        migrations.RemoveField(
            model_name="topicodiscussao",
            name="fechado",
        ),
        migrations.AddField(
            model_name="respostadiscussao",
            name="editado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="respostadiscussao",
            name="motivo_edicao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topicodiscussao",
            name="melhor_resposta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="topico_melhor_resposta",
                to="discussao.respostadiscussao",
            ),
        ),
        migrations.AddField(
            model_name="topicodiscussao",
            name="status",
            field=models.CharField(
                choices=[("aberto", "Aberto"), ("fechado", "Fechado")], default="aberto", max_length=7
            ),
        ),
        migrations.RemoveField(
            model_name="topicodiscussao",
            name="tags",
        ),
        migrations.AddField(
            model_name="topicodiscussao",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="topicos", to="discussao.tag"),
        ),
    ]
