# Generated by Django 5.2.5 on 2025-08-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussao", "0003_timestamp_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicodiscussao",
            name="publico_alvo",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Todos"),
                    (1, "Apenas nucleados"),
                    (2, "Apenas associados"),
                    (3, "Apenas organizadores"),
                    (4, "Apenas parceiros"),
                ]
            ),
        ),
    ]
