# Generated by Django 5.2.5 on 2025-08-16 15:41

import discussao.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussao", "0003_timestamp_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="respostadiscussao",
            name="arquivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="discussoes/arquivos/",
                validators=[discussao.validators.validate_attachment],
            ),
        ),
    ]
