# Generated by Django 5.2.2 on 2025-08-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussao", "0004_tag_remove_topicodiscussao_fechado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interacaodiscussao",
            name="tipo",
        ),
        migrations.AddField(
            model_name="interacaodiscussao",
            name="valor",
            field=models.SmallIntegerField(choices=[(1, "Curtir"), (-1, "Não Curtir")], default=1),
        ),
    ]
