# Generated by Django 5.2.5 on 2025-08-21 15:10

import uuid
from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Tag = apps.get_model("discussao", "Tag")
    for tag in Tag.objects.all():
        tag.slug = slugify(tag.nome)
        tag.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("discussao", "0004_alter_topicodiscussao_publico_alvo"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(default=uuid.uuid4, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
