# Generated by Django 5.2.5 on 2025-08-19 23:15

from django.db import migrations, models


def map_publico_alvo(apps, schema_editor):
    TopicoDiscussao = apps.get_model("discussao", "TopicoDiscussao")
    TopicoDiscussao.objects.filter(publico_alvo=2).update(publico_alvo=1)


class Migration(migrations.Migration):
    dependencies = [
        ("discussao", "0004_alter_topicodiscussao_publico_alvo"),
    ]

    operations = [
        migrations.RunPython(map_publico_alvo, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="topicodiscussao",
            name="publico_alvo",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Todos"),
                    (1, "Apenas nucleados"),
                    (3, "Apenas organizadores"),
                    (4, "Apenas parceiros"),
                ]
            ),
        ),
    ]
