# Generated by Django 5.2.5 on 2025-08-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussao", "0005_remove_associados_publico_alvo"),
        ("discussao", "0005_tag_slug"),
    ]

    operations = []
