# Generated by Django 5.2.2 on 2025-08-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussao", "0006_categoriadiscussao_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topicodiscussao",
            name="status",
        ),
        migrations.AddField(
            model_name="topicodiscussao",
            name="fechado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="respostadiscussao",
            name="motivo_edicao",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="tag",
            name="nome",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
