# Generated by Django 5.2.5 on 2025-08-23 13:22

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0005_remove_avaliacao_feedback_from_inscricao"),
        ("discussao", "0006_merge_20250821_1829"),
        ("nucleos", "0008_nucleo_ativo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="respostadiscussao",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="discussao_r_search__861964_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="topicodiscussao",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="discussao_t_search__ed0a2a_gin"
            ),
        ),
    ]
