# Generated by Django 5.2.2 on 2025-08-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussao", "0007_remove_topicodiscussao_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicodiscussao",
            name="resolvido",
            field=models.BooleanField(default=False),
        ),
    ]
