# Generated by Django 5.2.2 on 2025-08-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussao", "0008_topicodiscussao_resolvido"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
