# Generated by Django 5.2.2 on 2025-08-06 17:10

import discussao.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussao", "0009_tag_deleted_tag_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="respostadiscussao",
            name="search_vector",
            field=discussao.models.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="topicodiscussao",
            name="search_vector",
            field=discussao.models.SearchVectorField(blank=True, editable=False, null=True),
        ),
    ]
