# Generated by Django 5.2.5 on 2025-08-08 18:44

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatChannelCategory",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Categoria de Canal",
                "verbose_name_plural": "Categorias de Canal",
            },
        ),
        migrations.CreateModel(
            name="ChatChannel",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "contexto_tipo",
                    models.CharField(
                        choices=[
                            ("privado", "Privado"),
                            ("nucleo", "Núcleo"),
                            ("evento", "Evento"),
                            ("organizacao", "Organização"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contexto_id", models.UUIDField(blank=True, null=True)),
                ("titulo", models.CharField(blank=True, max_length=200, null=True)),
                ("descricao", models.TextField(blank=True)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="chat/avatars/")),
                ("e2ee_habilitado", models.BooleanField(default=False)),
                (
                    "retencao_dias",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quantidade de dias para manter mensagens antes da remoção automática",
                        null=True,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="channels",
                        to="chat.chatchannelcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Canal de Chat",
                "verbose_name_plural": "Canais de Chat",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("text", "Texto"), ("image", "Imagem"), ("video", "Vídeo"), ("file", "Arquivo")],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("conteudo", models.TextField(blank=True)),
                ("conteudo_cifrado", models.TextField(blank=True)),
                ("arquivo", models.FileField(blank=True, null=True, upload_to="chat/arquivos/")),
                ("pinned_at", models.DateTimeField(blank=True, null=True)),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                ("is_spam", models.BooleanField(default=False)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="chat.chatchannel"
                    ),
                ),
                (
                    "lido_por",
                    models.ManyToManyField(blank=True, related_name="mensagens_lidas", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "remetente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens_enviadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="respostas",
                        to="chat.chatmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="ChatAttachment",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("arquivo", models.FileField(upload_to="chat/attachments/")),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("tamanho", models.PositiveIntegerField(default=0)),
                ("thumb_url", models.URLField(blank=True)),
                ("preview_ready", models.BooleanField(default=False)),
                ("infected", models.BooleanField(default=False)),
                (
                    "mensagem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat.chatmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo",
                "verbose_name_plural": "Anexos",
            },
        ),
        migrations.CreateModel(
            name="ChatMessageReaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("emoji", models.CharField(max_length=32)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reaction_details",
                        to="chat.chatmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reação",
                "verbose_name_plural": "Reações",
                "unique_together": {("message", "user", "emoji")},
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="reactions",
            field=models.ManyToManyField(
                blank=True,
                related_name="message_reactions",
                through="chat.ChatMessageReaction",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ChatModerationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Aprovar"),
                            ("remove", "Remover"),
                            ("edit", "Editar"),
                            ("create_item", "Criar item"),
                            ("retencao", "Retenção"),
                            ("spam", "Spam"),
                        ],
                        max_length=20,
                    ),
                ),
                ("previous_content", models.TextField(blank=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="moderations", to="chat.chatmessage"
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_moderations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Moderação",
                "verbose_name_plural": "Logs de Moderação",
            },
        ),
        migrations.CreateModel(
            name="ChatNotification",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("lido", models.BooleanField(default=False)),
                (
                    "mensagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="notificacoes", to="chat.chatmessage"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
            },
        ),
        migrations.CreateModel(
            name="RelatorioChatExport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("formato", models.CharField(max_length=10)),
                ("status", models.CharField(default="gerando", max_length=20)),
                ("arquivo_url", models.URLField(blank=True)),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.chatchannel")),
                (
                    "gerado_por",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Relatório de Exportação",
                "verbose_name_plural": "Relatórios de Exportação",
            },
        ),
        migrations.CreateModel(
            name="ResumoChat",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("periodo", models.CharField(choices=[("diario", "Diário"), ("semanal", "Semanal")], max_length=10)),
                ("conteudo", models.TextField()),
                ("gerado_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("detalhes", models.JSONField(blank=True, default=dict)),
                (
                    "canal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="resumos", to="chat.chatchannel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Resumo de Chat",
                "verbose_name_plural": "Resumos de Chat",
            },
        ),
        migrations.CreateModel(
            name="TrendingTopic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("palavra", models.CharField(max_length=100)),
                ("frequencia", models.PositiveIntegerField()),
                ("periodo_inicio", models.DateTimeField()),
                ("periodo_fim", models.DateTimeField()),
                (
                    "canal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trending_topics",
                        to="chat.chatchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tópico em Alta",
                "verbose_name_plural": "Tópicos em Alta",
                "ordering": ["-frequencia"],
            },
        ),
        migrations.CreateModel(
            name="UserChatPreference",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "tema",
                    models.CharField(
                        choices=[("claro", "Claro"), ("escuro", "Escuro")], default="claro", max_length=10
                    ),
                ),
                ("buscas_salvas", models.JSONField(blank=True, default=list)),
                ("resumo_diario", models.BooleanField(default=False)),
                ("resumo_semanal", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferência de Chat",
                "verbose_name_plural": "Preferências de Chat",
            },
        ),
        migrations.CreateModel(
            name="ChatFavorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="favorited_by", to="chat.chatmessage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorito",
                "verbose_name_plural": "Favoritos",
                "indexes": [models.Index(fields=["user", "message"], name="chat_chatfa_user_id_7580ff_idx")],
                "unique_together": {("user", "message")},
            },
        ),
        migrations.CreateModel(
            name="ChatMessageFlag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="flags", to="chat.chatmessage"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Sinalização",
                "verbose_name_plural": "Sinalizações",
                "unique_together": {("message", "user")},
            },
        ),
        migrations.CreateModel(
            name="ChatParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_owner", models.BooleanField(default=False)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="chat.chatchannel"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
                "unique_together": {("user", "channel")},
            },
        ),
    ]
