# Generated by Django 5.2.2 on 2025-07-18 22:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "__first__"),
        ("nucleos", "0001_initial"),
        ("organizacoes", "0002_alter_organizacao_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(blank=True, max_length=200, null=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "tipo_conversa",
                    models.CharField(
                        choices=[
                            ("direta", "Mensagem direta"),
                            ("grupo", "Grupo global"),
                            ("organizacao", "Grupo da Organização"),
                            ("nucleo", "Grupo do Núcleo"),
                            ("evento", "Grupo do Evento"),
                        ],
                        default="direta",
                        max_length=12,
                    ),
                ),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="chat/avatars/")),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="agenda.evento"
                    ),
                ),
                (
                    "nucleo",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nucleos.nucleo"
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizacoes.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversa",
                "verbose_name_plural": "Conversas",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("conteudo", models.TextField(blank=True)),
                ("arquivo", models.FileField(blank=True, null=True, upload_to="chat/arquivos/")),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="chat.chatconversation"
                    ),
                ),
                (
                    "lido_por",
                    models.ManyToManyField(blank=True, related_name="mensagens_lidas", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lido", models.BooleanField(default=False)),
                (
                    "mensagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="notificacoes", to="chat.chatmessage"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
            },
        ),
        migrations.CreateModel(
            name="ChatParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_admin", models.BooleanField(default=False)),
                ("is_owner", models.BooleanField(default=False)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="chat.chatconversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
                "unique_together": {("user", "conversation")},
            },
        ),
    ]
