# Generated by Django 5.2.5 on 2025-08-14 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessagereaction",
            name="created",
        ),
        migrations.RemoveField(
            model_name="resumochat",
            name="gerado_em",
        ),
        migrations.AddField(
            model_name="chatmessagereaction",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="chatmessagereaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="resumochat",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="resumochat",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="trendingtopic",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="trendingtopic",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
