# Generated by Django 5.2.2 on 2025-06-24 23:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensagem",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="mensagem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
