# Generated by Django 5.2.2 on 2025-07-21 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("organizacoes", "0002_alter_organizacao_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="organizacao",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="organizacoes.organizacao"
            ),
        ),
    ]
