# Generated by Django 5.2.2 on 2025-08-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatattachment",
            name="infected",
            field=models.BooleanField(default=False),
        ),
    ]
