# Generated by Django 5.2.2 on 2025-08-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatattachment_infected"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_spam",
            field=models.BooleanField(default=False),
        ),
    ]
