# Generated by Django 5.2.2 on 2025-07-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_add_organizacao_to_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="pinned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="reactions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="tipo",
            field=models.CharField(
                choices=[("text", "Texto"), ("image", "Imagem"), ("video", "Vídeo"), ("file", "Arquivo")],
                default="text",
                max_length=10,
            ),
        ),
    ]
