# Generated by Django 5.2.2 on 2025-07-25 22:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatmessage_pinned_at_chatmessage_reactions_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatorioChatExport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("formato", models.CharField(max_length=10)),
                ("arquivo_url", models.URLField()),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.chatconversation")),
                (
                    "gerado_por",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Relatório de Exportação",
                "verbose_name_plural": "Relatórios de Exportação",
            },
        ),
    ]
