# Generated by Django 5.2.2 on 2025-06-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_mensagem_destinatario_alter_mensagem_remetente_and_more"),
        ("chat", "0003_notificacao"),
    ]

    operations = []
