# Generated by Django 5.2.2 on 2025-08-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatmessage_is_spam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmoderationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("approve", "Aprovar"),
                    ("remove", "Remover"),
                    ("edit", "Editar"),
                    ("create_item", "Criar item"),
                    ("retencao", "Retenção"),
                    ("spam", "Spam"),
                ],
                max_length=20,
            ),
        ),
    ]
