# Generated by Django 5.2.5 on 2025-08-14 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_chatchannelcategory_channelnotification_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="chatmessageflag",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="chatmessageflag",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="chatattachment",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="chatattachment",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="chatmoderationlog",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="chatmoderationlog",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="userchatpreference",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="userchatpreference",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.AlterModelOptions(
            name="chatmessage",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
            },
        ),
    ]
