# Generated by Django 5.2.2 on 2025-08-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_trendingtopic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trendingtopic",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
