# Generated by Django 5.2.5 on 2025-08-14 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_chatattachment_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chatmessagereaction",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="chatmessagereaction",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessagereaction",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="chatmessagereaction",
            unique_together={("message", "user", "emoji", "deleted")},
        ),
    ]
