# Generated by Django 5.2.2 on 2025-07-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_moderacao_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="descricao",
            field=models.TextField(blank=True),
        ),
    ]
