# Generated by Django 5.2.5 on 2025-08-14 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_alter_chatmessageflag_unique_together_and_more"),
        ("chat", "0007_alter_chatmessagereaction_unique_together_and_more"),
    ]

    operations = []
