# Generated by Django 5.2.2 on 2025-08-02 00:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_alter_chatmessage_options_remove_chatmessage_sender_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatChannel",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "contexto_tipo",
                    models.CharField(
                        choices=[
                            ("privado", "Privado"),
                            ("nucleo", "Núcleo"),
                            ("evento", "Evento"),
                            ("organizacao", "Organização"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contexto_id", models.UUIDField(blank=True, null=True)),
                ("titulo", models.CharField(blank=True, max_length=200, null=True)),
                ("descricao", models.TextField(blank=True)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="chat/avatars/")),
            ],
            options={
                "verbose_name": "Canal de Chat",
                "verbose_name_plural": "Canais de Chat",
            },
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="organizacao",
        ),
        migrations.AlterUniqueTogether(
            name="chatparticipant",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chatchannel",
            ),
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="chat.chatchannel",
            ),
        ),
        migrations.AlterField(
            model_name="relatoriochatexport",
            name="channel",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.chatchannel"),
        ),
        migrations.AlterUniqueTogether(
            name="chatparticipant",
            unique_together={("user", "channel")},
        ),
    ]
