# Generated by Django 5.2.5 on 2025-08-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_merge_20250814_1936"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchatpreference",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userchatpreference",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
