# Generated by Django 5.2.2 on 2025-08-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_chatchannel_remove_chatmessage_conversation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatoriochatexport",
            name="status",
            field=models.CharField(default="gerando", max_length=20),
        ),
        migrations.AlterField(
            model_name="relatoriochatexport",
            name="arquivo_url",
            field=models.URLField(blank=True),
        ),
    ]
