# Generated by Django 5.2.5 on 2025-08-14 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_chatnotification_deleted_chatnotification_deleted_at"),
        ("chat", "0009_userchatpreference_deleted_and_more"),
    ]

    operations = []
