# Generated by Django 5.2.5 on 2025-08-14 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_merge_20250814_1958"),
        ("chat", "0011_resumochat_deleted_resumochat_deleted_at"),
    ]

    operations = []
