# Generated by Django 5.2.2 on 2025-08-02 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_migrate_conversations_to_channels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatparticipant",
            name="conversation",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="conversation",
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="chat.chatchannel"
            ),
        ),
        migrations.AlterField(
            model_name="chatparticipant",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="chat.chatchannel"
            ),
        ),
        migrations.DeleteModel(
            name="ChatConversation",
        ),
    ]
