# Generated by Django 5.2.2 on 2025-08-04 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_remove_chatparticipant_conversation_and_more"),
    ]

    def copy_timestamps(apps, schema_editor):
        models_to_update = [
            "ChatChannel",
            "ChatMessage",
            "ChatNotification",
            "ChatMessageFlag",
            "RelatorioChatExport",
            "ChatModerationLog",
        ]
        for model_name in models_to_update:
            Model = apps.get_model("chat", model_name)
            for obj in Model.objects.all():
                ts = getattr(obj, "timestamp", obj.created_at)
                obj.created = ts
                obj.modified = obj.updated_at
                obj.save(update_fields=["created", "modified"])

    operations = [
        migrations.AddField(
            model_name="chatchannel",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatchannel",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="chatchannel",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatchannel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatnotification",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatnotification",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="chatmessageflag",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatmessageflag",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="relatoriochatexport",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relatoriochatexport",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="chatmoderationlog",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatmoderationlog",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(copy_timestamps, migrations.RunPython.noop),
        migrations.RemoveField(model_name="chatchannel", name="created_at"),
        migrations.RemoveField(model_name="chatchannel", name="updated_at"),
        migrations.RemoveField(model_name="chatmessage", name="created_at"),
        migrations.RemoveField(model_name="chatmessage", name="updated_at"),
        migrations.RemoveField(model_name="chatmessage", name="timestamp"),
        migrations.RemoveField(model_name="chatnotification", name="created_at"),
        migrations.RemoveField(model_name="chatnotification", name="updated_at"),
        migrations.RemoveField(model_name="chatmessageflag", name="created_at"),
        migrations.RemoveField(model_name="chatmessageflag", name="updated_at"),
        migrations.RemoveField(model_name="relatoriochatexport", name="created_at"),
        migrations.RemoveField(model_name="relatoriochatexport", name="updated_at"),
        migrations.RemoveField(model_name="chatmoderationlog", name="created_at"),
        migrations.RemoveField(model_name="chatmoderationlog", name="updated_at"),
    ]
