# Generated by Django 5.2.2 on 2025-08-04 15:24

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_refatorar_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["created"], "verbose_name": "Mensagem", "verbose_name_plural": "Mensagens"},
        ),
        migrations.AlterField(
            model_name="chatchannel",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="chatchannel",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="chatmessageflag",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="chatmessageflag",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="chatmoderationlog",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="chatmoderationlog",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="chatnotification",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="chatnotification",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="chatparticipant",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="chatparticipant",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="relatoriochatexport",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="relatoriochatexport",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
    ]
