# Generated by Django 5.2.5 on 2025-08-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_chatmessage_e2ee_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatoriochatexport",
            name="arquivo_path",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
