# Generated by Django 5.2.2 on 2025-08-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_alter_chatmessage_options_alter_chatchannel_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmoderationlog",
            name="previous_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="chatmoderationlog",
            name="action",
            field=models.CharField(
                choices=[("approve", "Aprovar"), ("remove", "Remover"), ("edit", "Editar")], max_length=10
            ),
        ),
    ]
