# Generated by Django 5.2.2 on 2025-08-05 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_chatmoderationlog_previous_content_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="reactions",
        ),
        migrations.CreateModel(
            name="ChatMessageReaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("emoji", models.CharField(max_length=32)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reaction_details",
                        to="chat.chatmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reação",
                "verbose_name_plural": "Reações",
                "unique_together": {("message", "user", "emoji")},
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="reactions",
            field=models.ManyToManyField(
                blank=True,
                related_name="message_reactions",
                through="chat.ChatMessageReaction",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
