# Generated by Django 5.2.2 on 2025-08-06 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_remove_chatmessage_reactions_chatmessagereaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="respostas",
                to="chat.chatmessage",
            ),
        ),
    ]
