# Generated by Django 5.2.5 on 2025-08-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_chatattachment_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatattachment",
            name="removed",
            field=models.BooleanField(default=False),
        ),
    ]
