# Generated by Django 5.2.2 on 2025-08-06 21:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0018_chatfavorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumoChat",
            fields=[
                (
                    "id",
                    models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "periodo",
                    models.CharField(
                        choices=[("diario", "Diário"), ("semanal", "Semanal")],
                        max_length=10,
                    ),
                ),
                ("conteudo", models.TextField()),
                (
                    "gerado_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("detalhes", models.JSONField(blank=True, default=dict)),
                (
                    "canal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumos",
                        to="chat.chatchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resumo de Chat",
                "verbose_name_plural": "Resumos de Chat",
            },
        ),
    ]
