# Generated by Django 5.2.2 on 2025-08-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0021_chatattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatchannel",
            name="e2ee_habilitado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="conteudo_cifrado",
            field=models.TextField(blank=True),
        ),
    ]
