# Generated by Django 5.2.2 on 2025-08-07 17:57

import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0023_chatchannel_retencao_dias"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="chatfavorite",
            new_name="chat_chatfa_user_id_7580ff_idx",
            old_name="chatfav_user_msg_idx",
        ),
        migrations.AlterField(
            model_name="chatfavorite",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="chatfavorite",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="chatmoderationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("approve", "Aprovar"),
                    ("remove", "Remover"),
                    ("edit", "Editar"),
                    ("create_item", "Criar item"),
                    ("retencao", "Retenção"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="resumochat",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
