# Generated by Django 5.2.2 on 2025-08-07 18:25

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0025_merge_20250807_1514"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserChatPreference",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "tema",
                    models.CharField(
                        choices=[("claro", "Claro"), ("escuro", "Escuro")], default="claro", max_length=10
                    ),
                ),
                ("buscas_salvas", models.JSONField(blank=True, default=list)),
                ("resumo_diario", models.BooleanField(default=False)),
                ("resumo_semanal", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferência de Chat",
                "verbose_name_plural": "Preferências de Chat",
            },
        ),
    ]
