# Generated by Django 5.2.5 on 2025-08-08 18:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardConfig",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("config", models.JSONField()),
                ("publico", models.BooleanField(default=False)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "get_latest_by": "modified",
            },
        ),
        migrations.CreateModel(
            name="DashboardFilter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=100)),
                ("filtros", models.JSONField()),
                ("publico", models.BooleanField(default=False)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DashboardLayout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=100)),
                ("layout_json", models.JSONField()),
                ("publico", models.BooleanField(default=False)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "get_latest_by": "modified",
            },
        ),
    ]
