# Generated by Django 5.2.2 on 2025-08-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_achievement"),
        ("dashboard", "0002_dashboardlayout"),
    ]

    operations = []
