# Generated by Django 5.2.2 on 2025-08-04 13:19

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_dashboardconfig"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dashboardconfig",
            options={"get_latest_by": "modified"},
        ),
        migrations.RemoveField(
            model_name="dashboardconfig",
            name="created_at",
        ),
        migrations.AddField(
            model_name="dashboardconfig",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="created"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dashboardconfig",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
        ),
    ]
