# Generated by Django 5.2.5 on 2025-08-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_achievement_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="achievement",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userachievement",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userachievement",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
