# Generated by Django 5.2.2 on 2025-08-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_migrate_dashboardfilter_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardfilter",
            name="publico",
            field=models.BooleanField(default=False),
        ),
    ]
