# Generated by Django 5.2.2 on 2025-07-15 16:51

import accounts.models
import core.fields
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("nucleos", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Tag de Mídia",
                "verbose_name_plural": "Tags de Mídia",
            },
        ),
        migrations.CreateModel(
            name="UserType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("descricao", models.CharField(max_length=20, verbose_name="Descrição")),
            ],
            options={
                "verbose_name": "Tipo de Usuário",
                "verbose_name_plural": "Tipos de Usuário",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254, unique=True, verbose_name="email address")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Ex.: +55 48 99999-0000",
                        max_length=128,
                        null=True,
                        region="BR",
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Rua, número, complemento, cidade/UF",
                        max_length=255,
                        verbose_name="Endereço",
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True, verbose_name="Data de nascimento")),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Digite um CPF válido no formato 000.000.000-00.",
                                regex="^\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}$",
                            )
                        ],
                        verbose_name="CPF",
                    ),
                ),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="avatars/")),
                ("bio", models.TextField(blank=True)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("genero", models.CharField(blank=True, max_length=1)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("endereco", models.CharField(blank=True, max_length=255)),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(blank=True, max_length=2)),
                ("cep", models.CharField(blank=True, max_length=10)),
                ("facebook", core.fields.URLField(blank=True)),
                ("twitter", core.fields.URLField(blank=True)),
                ("instagram", core.fields.URLField(blank=True)),
                ("linkedin", core.fields.URLField(blank=True)),
                ("website", core.fields.URLField(blank=True)),
                ("idioma", models.CharField(blank=True, max_length=10)),
                ("fuso_horario", models.CharField(blank=True, max_length=50)),
                ("perfil_publico", models.BooleanField(default=True)),
                ("mostrar_email", models.BooleanField(default=True)),
                ("mostrar_telefone", models.BooleanField(default=False)),
                ("connections", models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                (
                    "followers",
                    models.ManyToManyField(blank=True, related_name="following", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "nucleo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usuarios_principais",
                        to="nucleos.nucleo",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        default=3,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="accounts.usertype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
            managers=[
                ("objects", accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_conexoes", models.BooleanField(default=True)),
                ("email_mensagens", models.BooleanField(default=True)),
                ("email_eventos", models.BooleanField(default=True)),
                ("email_newsletter", models.BooleanField(default=True)),
                ("sistema_conexoes", models.BooleanField(default=True)),
                ("sistema_mensagens", models.BooleanField(default=True)),
                ("sistema_eventos", models.BooleanField(default=True)),
                ("sistema_comentarios", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Notificação",
                "verbose_name_plural": "Configurações de Notificação",
            },
        ),
        migrations.CreateModel(
            name="UserMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="user_media/")),
                ("descricao", models.CharField(blank=True, max_length=255, verbose_name="Descrição")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.ManyToManyField(blank=True, related_name="medias", to="accounts.mediatag")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="medias", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Mídia do Usuário",
                "verbose_name_plural": "Mídias do Usuário",
            },
        ),
    ]
