# Generated by Django 5.2.4 on 2025-07-15 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("organizacoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organizacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="organizacoes.organizacao",
            ),
        ),
    ]
