# Generated by Django 5.2.2 on 2025-08-07 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("nucleos", "0001_initial"),
        ("organizacoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nucleo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios_principais",
                to="nucleos.nucleo",
                verbose_name="Núcleo",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organizacao",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="organizacoes.organizacao",
                verbose_name="Organização",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="accounttoken",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="account_tokens", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="usuario",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="security_events", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="usermedia",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="medias", to="accounts.mediatag"),
        ),
        migrations.AddField(
            model_name="usermedia",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="medias", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
