# Generated by Django 5.2.2 on 2025-06-12 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_avatar_user_bio_user_cep_user_cidade_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_conexoes", models.BooleanField(default=True)),
                ("email_mensagens", models.BooleanField(default=True)),
                ("email_eventos", models.BooleanField(default=True)),
                ("email_newsletter", models.BooleanField(default=True)),
                ("sistema_conexoes", models.BooleanField(default=True)),
                ("sistema_mensagens", models.BooleanField(default=True)),
                ("sistema_eventos", models.BooleanField(default=True)),
                ("sistema_comentarios", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Notificação",
                "verbose_name_plural": "Configurações de Notificação",
            },
        ),
    ]
