# Generated by Django 5.2.4 on 2025-07-16 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_organizacao"),
        ("nucleos", "0002_nucleo_membros"),
        ("organizacoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_associado",
            field=models.BooleanField(default=False, verbose_name="É associado"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_coordenador",
            field=models.BooleanField(default=False, verbose_name="É coordenador"),
        ),
        migrations.AlterField(
            model_name="user",
            name="nucleo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios_principais",
                to="nucleos.nucleo",
                verbose_name="Núcleo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organizacao",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="organizacoes.organizacao",
                verbose_name="Organização",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.usertype",
            ),
        ),
    ]
