# Generated by Django 5.2.5 on 2025-08-19 15:04

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                unique=True,
                validators=[accounts.validators.cpf_validator],
                verbose_name="CPF",
            ),
        ),
    ]
