# Generated by Django 5.2.2 on 2025-07-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tipo",
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("root", "ROOT"),
                    ("admin", "ADMIN"),
                    ("coordenador", "COORDENADOR"),
                    ("nucleado", "NUCLEADO"),
                    ("associado", "ASSOCIADO"),
                    ("convidado", "CONVIDADO"),
                ],
                default="convidado",
                max_length=20,
                verbose_name="Tipo de Usuário",
            ),
        ),
        migrations.DeleteModel(
            name="UserType",
        ),
    ]
