# Generated by Django 5.2.2 on 2025-07-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="biografia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="users/capas/"),
        ),
        migrations.AddField(
            model_name="user",
            name="fone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="nome_completo",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
