# Generated by Django 5.2.2 on 2025-06-22 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_cpf"),
        ("organizacoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organizacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="organizacoes.organizacao",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("superadmin", "Superadmin"),
                    ("admin", "Admin"),
                    ("gerente", "Gerente"),
                    ("cliente", "Cliente"),
                ],
                default="cliente",
                max_length=20,
            ),
        ),
    ]
