# Generated by Django 5.2.5 on 2025-08-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttoken",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("email_confirmation", "Confirmação de Email"),
                    ("password_reset", "Redefinição de Senha"),
                    ("cancel_delete", "Cancelar Exclusão"),
                ],
                max_length=20,
            ),
        ),
    ]
