# Generated by Django 5.2.4 on 2025-07-16 13:59

from django.db import migrations, models


def atribuir_organizacao_padrao(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Organizacao = apps.get_model("organizacoes", "Organizacao")
    organizacao_padrao, _ = Organizacao.objects.get_or_create(nome="Organização Padrão")
    User.objects.filter(organizacao__isnull=True).update(organizacao=organizacao_padrao)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_is_associado_user_is_coordenador_and_more"),
    ]

    operations = [
        migrations.RunPython(atribuir_organizacao_padrao),
    ]
