# Generated by Django 5.2.2 on 2025-07-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_user_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="redes_sociais",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
