# Generated by Django 5.2.2 on 2025-07-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_redes_sociais"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="redes_sociais",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
