# Generated by Django 5.2.2 on 2025-06-22 20:36

import django.db.models.deletion
from django.db import migrations, models


def create_user_types(apps, schema_editor):
    UserType = apps.get_model("accounts", "UserType")
    UserType.objects.bulk_create(
        [
            UserType(id=1, descricao="admin"),
            UserType(id=2, descricao="manager"),
            UserType(id=3, descricao="client"),
            UserType(id=4, descricao="root"),
        ]
    )


def migrate_user_tipos(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    mapping = {
        "admin": 1,
        "gerente": 2,
        "manager": 2,
        "cliente": 3,
        "client": 3,
        "superadmin": 4,
        "root": 4,
    }
    for user in User.objects.all():
        tipo = getattr(user, "tipo")
        tipo_id = mapping.get(tipo, 3)
        user.tipo_new_id = tipo_id
        user.save(update_fields=["tipo_new"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_create_root_superadmin"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descricao", models.CharField("Descrição", max_length=20)),
            ],
            options={
                "verbose_name": "Tipo de Usuário",
                "verbose_name_plural": "Tipos de Usuário",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="tipo_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                default=3,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.usertype",
            ),
        ),
        migrations.RunPython(create_user_types, migrations.RunPython.noop),
        migrations.RunPython(migrate_user_tipos, migrations.RunPython.noop),
        migrations.RemoveField(model_name="user", name="tipo"),
        migrations.RenameField(model_name="user", old_name="tipo_new", new_name="tipo"),
    ]
