# Generated by Django 5.2.5 on 2025-08-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_user_login_lock_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="user",
            name="fone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="user",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nome_completo",
        ),
        migrations.RemoveField(
            model_name="user",
            name="twitter",
        ),
        migrations.RemoveField(
            model_name="user",
            name="website",
        ),
    ]
