# Generated by Django 5.2.2 on 2025-06-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_usertypes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertype",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
