# Generated by Django 5.2.2 on 2025-07-24 20:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_mediatag_created_at_and_more"),
        ("nucleos", "0001_initial"),
        ("organizacoes", "0003_alter_organizacao_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="cidade",
        ),
        migrations.RemoveField(
            model_name="user",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="user",
            name="fuso_horario",
        ),
        migrations.RemoveField(
            model_name="user",
            name="idioma",
        ),
        migrations.RemoveField(
            model_name="user",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_coordenador",
        ),
        migrations.RemoveField(
            model_name="user",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="mostrar_email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="mostrar_telefone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nucleo",
        ),
        migrations.RemoveField(
            model_name="user",
            name="perfil_publico",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="twitter",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="website",
        ),
        migrations.AddField(
            model_name="user",
            name="nucleos",
            field=models.ManyToManyField(
                related_name="usuarios", through="nucleos.ParticipacaoNucleo", to="nucleos.nucleo"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="usuarios/avatars/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="cep",
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name="user",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="usuarios/capas/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Digite um CPF válido no formato 000.000.000-00.",
                        regex="^\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="fone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_associado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="nome_completo",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="organizacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to="organizacoes.organizacao",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="redes_sociais",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name="ConfiguracaoDeConta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receber_notificacoes_email", models.BooleanField(default=True)),
                ("receber_notificacoes_whatsapp", models.BooleanField(default=False)),
                ("tema_escuro", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Conta",
                "verbose_name_plural": "Configurações de Conta",
            },
        ),
        migrations.DeleteModel(
            name="NotificationSettings",
        ),
    ]
