# Generated by Django 5.2.5 on 2025-09-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermedia",
            name="publico",
            field=models.BooleanField(default=True),
        ),
    ]
