# Generated by Django 5.2.2 on 2025-07-26 16:17

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_securityevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="two_factor_secret",
            field=core.fields.EncryptedCharField(blank=True, max_length=128, null=True),
        ),
    ]
