# Generated by Django 5.2.5 on 2025-09-12 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_usermedia_publico"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usermedia",
            options={"verbose_name": "Mídia do Usuário", "verbose_name_plural": "Portfólio do Usuário"},
        ),
    ]
