# Generated by Django 5.2.2 on 2025-06-24 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_usermedia"),
        ("nucleos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nucleo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios_principais",
                to="nucleos.nucleo",
            ),
        ),
    ]
