# Generated by Django 5.2.5 on 2025-09-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_usermedia_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cnpj",
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name="CNPJ"),
        ),
        migrations.AddField(
            model_name="user",
            name="razao_social",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Razão Social"),
        ),
    ]
