# Generated by Django 5.2.2 on 2025-08-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_user_two_factor_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            "UPDATE accounts_user SET email_confirmed = 1 WHERE is_active = 1",
            migrations.RunSQL.noop,
        ),
    ]
