# Generated by Django 5.2.2 on 2025-06-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_notificationsettings_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermedia",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Descrição"
            ),
        ),
    ]
