# Generated by Django 5.2.5 on 2025-09-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_user_cnpj_user_razao_social"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nome_fantasia",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nome fantasia"),
        ),
    ]
