# Generated by Django 5.2.5 on 2025-09-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_user_nome_fantasia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
