# Generated by Django 5.2.2 on 2025-06-26 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_usermedia_descricao"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Tag de Mídia",
                "verbose_name_plural": "Tags de Mídia",
            },
        ),
        migrations.AddField(
            model_name="usermedia",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="medias", to="accounts.mediatag"
            ),
        ),
    ]
