# Generated by Django 5.2.2 on 2025-08-04 23:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_unify_timestamps_and_softdelete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttoken",
            name="codigo",
            field=models.CharField(
                db_index=True, default=accounts.models.generate_secure_token, max_length=64, unique=True
            ),
        ),
    ]
