# Generated by Django 5.2.5 on 2025-09-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_user_birth_date_remove_user_last_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="first_name",
            new_name="contato",
        ),
        migrations.AlterField(
            model_name="user",
            name="contato",
            field=models.CharField("Contato", blank=True, max_length=150),
        ),
    ]
