# Generated by Django 5.2.2 on 2025-07-05 14:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_mediatag_usermedia_tags"),
        ("nucleos", "0002_nucleo_created_at_nucleo_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenAcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codigo",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "tipo_destino",
                    models.CharField(
                        choices=[
                            ("admin", "admin"),
                            ("gerente", "gerente"),
                            ("cliente", "cliente"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("novo", "não usado"),
                            ("usado", "usado"),
                            ("expirado", "expirado"),
                        ],
                        default="novo",
                        max_length=10,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_expiracao", models.DateTimeField()),
                (
                    "gerado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens_gerados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nucleo_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens",
                        to="nucleos.nucleo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Acesso",
                "verbose_name_plural": "Tokens de Acesso",
            },
        ),
    ]
