# Generated by Django 5.2.2 on 2025-08-05 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_accounttoken_codigo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NotificationSettings",
        ),
    ]
