# Generated by Django 5.2.5 on 2025-09-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_remove_user_first_name_user_contato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("root", "Root"),
                    ("admin", "Admin"),
                    ("coordenador", "Coordenador"),
                    ("nucleado", "Nucleado"),
                    ("associado", "Associado"),
                    ("convidado", "Convidado"),
                ],
                default="convidado",
                max_length=20,
                verbose_name="Tipo de Usuário",
            ),
        ),
    ]
