# Generated by Django 5.2.2 on 2025-07-09 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_tokenacesso"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TokenAcesso",
        ),
    ]
