# Generated by Django 5.2.2 on 2025-08-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_delete_notificationsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chave_publica",
            field=models.TextField(blank=True, null=True, verbose_name="Chave pública"),
        ),
    ]
