# Generated by Django 5.2.5 on 2025-09-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("root", "Root"),
                    ("admin", "Admin"),
                    ("coordenador", "Coordenador"),
                    ("nucleado", "Nucleado"),
                    ("associado", "Associado"),
                    ("convidado", "Convidado"),
                    ("operador", "Operador"),
                    ("consultor", "Consultor"),
                ],
                default="convidado",
                max_length=20,
                verbose_name="Tipo de Usuário",
            ),
        ),
    ]
