# Generated by Django 5.2.5 on 2025-10-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_user_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="area_atuacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tecnologia", "Tecnologia da Informação"),
                    ("comercio", "Comércio e Varejo"),
                    ("industria", "Indústria e Produção"),
                    ("construcao", "Construção Civil e Engenharia"),
                    ("educacao", "Educação e Treinamento"),
                    ("saude", "Saúde e Bem-Estar"),
                    ("alimentacao", "Alimentação e Gastronomia"),
                    ("agro", "Agropecuária e Meio Ambiente"),
                    ("financeiro", "Serviços Financeiros e Contábeis"),
                    ("juridico", "Serviços Jurídicos"),
                    ("marketing", "Marketing, Comunicação e Mídia"),
                    ("transporte", "Transporte e Logística"),
                    ("servicos", "Serviços Gerais e Terceirização"),
                    ("turismo", "Turismo, Hotelaria e Eventos"),
                    ("imobiliario", "Mercado Imobiliário"),
                    ("publico", "Setor Público e Governamental"),
                    ("social", "Associações, ONGs e Projetos Sociais"),
                    ("outros", "Outros Setores"),
                ],
                max_length=50,
                null=True,
                verbose_name="Área de atuação",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="descricao_atividade",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição da atividade"),
        ),
    ]
