# Generated by Django 5.2.2 on 2025-07-14 18:16

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_email_as_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook',
            field=core.fields.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=core.fields.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin',
            field=core.fields.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=core.fields.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=core.fields.URLField(blank=True),
        ),
    ]
