# Generated by Django 5.2.5 on 2025-11-05 15:59

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_user_area_atuacao_user_descricao_atividade"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("nucleos", "0012_alter_participacaonucleo_unique_together_and_more"),
        ("organizacoes", "0011_remove_organizacao_slug_and_rate_limit_multiplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=14, null=True, validators=[accounts.validators.cpf_validator], verbose_name="CPF"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cnpj__isnull", True), ("cnpj", ""), _connector="OR"),
                fields=("cpf",),
                name="accounts_user_unique_cpf_without_cnpj",
            ),
        ),
    ]
