# Generated by Django 5.2.5 on 2025-11-30 15:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def copy_perfil_feedback(apps, schema_editor):
    PerfilFeedback = apps.get_model("accounts", "PerfilFeedback")
    UserRating = apps.get_model("accounts", "UserRating")

    feedbacks = PerfilFeedback._base_manager.all()
    for feedback in feedbacks.iterator():
        UserRating.objects.get_or_create(
            rated_by_id=feedback.autor_id,
            rated_user_id=feedback.avaliado_id,
            defaults={
                "score": feedback.nota,
                "comment": feedback.comentario,
                "created_at": feedback.created_at,
                "updated_at": feedback.updated_at,
                "deleted": feedback.deleted,
                "deleted_at": feedback.deleted_at,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_user_managers_perfilfeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "rated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rated_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação de Usuário",
                "verbose_name_plural": "Avaliações de Usuários",
                "unique_together": {("rated_by", "rated_user")},
            },
        ),
        migrations.RunPython(copy_perfil_feedback, migrations.RunPython.noop),
    ]
