# Generated by Django 5.2.5 on 2025-12-11 18:11

from django.db import migrations, models


def sync_accounttoken_status(apps, schema_editor):
    AccountToken = apps.get_model("accounts", "AccountToken")
    AccountToken.objects.filter(used_at__isnull=False).update(status="utilizado")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_userrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttoken",
            name="status",
            field=models.CharField(
                choices=[("pendente", "Pendente"), ("confirmado", "Confirmado"), ("utilizado", "Utilizado")],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.RunPython(sync_accounttoken_status, migrations.RunPython.noop),
    ]
