# Generated by Django 5.2.5 on 2026-02-26 19:19

from django.db import migrations, models


def set_empty_cnpj_to_null(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(cnpj="").update(cnpj=None)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_fill_guest_organizacao"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("nucleos", "0013_nucleomidia"),
        ("organizacoes", "0017_organizacao_cep_contato_whatsapp_remove_cover"),
    ]

    operations = [
        migrations.RunPython(set_empty_cnpj_to_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="cnpj",
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name="CNPJ"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cnpj__isnull", False), models.Q(("cnpj", ""), _negated=True)),
                fields=("cnpj",),
                name="accounts_user_unique_cnpj_when_present",
            ),
        ),
    ]
