# Generated by Django 5.2.5 on 2026-03-05 22:44

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_mfa_email_and_challenge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="two_factor_secret",
            field=core.fields.EncryptedCharField(blank=True, max_length=512, null=True),
        ),
    ]
