# Generated by Django 5.2.5 on 2026-03-05 22:54

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_alter_user_two_factor_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="two_factor_secret",
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
