"""
Django settings for Hubx project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import base64
import os
from decimal import Decimal
from pathlib import Path

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Versão do HTMX utilizada nos templates
HTMX_VERSION = "1.9.12"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-f_(^m#wo6a9xfpmwi)8n7bo@k@gs!sp_(9-=jhi0%2r6o@2i^8"

# Chave para criptografia de campos sensíveis
FERNET_KEY = os.environ.get(
    "FERNET_KEY",
    base64.urlsafe_b64encode(SECRET_KEY.encode()[:32]).decode(),
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "testserver",
    "localhost",
    "127.0.0.1",
]

# Application definition

INSTALLED_APPS = [
    # ‑‑‑‑ Apps nativos do Django ‑‑‑‑
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # ‑‑‑‑ Terceiros (third‑party) ‑‑‑‑
    "rest_framework",
    "rest_framework.authtoken",
    "widget_tweaks",
    "django_select2",
    "phonenumber_field",
    "channels",
    # ‑‑‑‑ Apps da sua solução ‑‑‑‑
    "core",
    "dashboard",
    "empresas",
    "accounts.apps.AccountsConfig",
    "organizacoes",
    "tokens.apps.TokensConfig",
    "nucleos",
    "agenda",
    "chat",
    "feed",
    "discussao.apps.DiscussaoConfig",
    "configuracoes",
    "financeiro.apps.FinanceiroConfig",
    "notificacoes.apps.NotificacoesConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "configuracoes.middleware.UserLocaleMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Hubx.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.htmx_version",
            ],
        },
    },
]

WSGI_APPLICATION = "Hubx.wsgi.application"
ASGI_APPLICATION = "Hubx.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [("127.0.0.1", 6379)]},
    }
}

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "ATOMIC_REQUESTS": True,
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]
BCRYPT_ROUNDS = 12

# Internationalization
LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Sao_Paulo"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
USER_MEDIA_MAX_SIZE = 50 * 1024 * 1024  # 50MB
USER_MEDIA_ALLOWED_EXTS = [".jpg", ".jpeg", ".png", ".gif", ".pdf", ".mp4", ".webm"]

DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = DATA_UPLOAD_MAX_MEMORY_SIZE

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "accounts.User"

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/perfil/"

AUTHENTICATION_BACKENDS = [
    "accounts.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "tokens.auth.ApiTokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ]
}

# Valores padrão para mensalidades
MENSALIDADE_ASSOCIACAO = Decimal("50.00")
MENSALIDADE_NUCLEO = Decimal("30.00")
MENSALIDADE_VENCIMENTO_DIA = 10

# Celery Beat

CELERY_BEAT_SCHEDULE = {
    "notificar_inadimplencia": {
        "task": "financeiro.tasks.notificar_inadimplencia.notificar_inadimplencia",
        "schedule": crontab(minute=0, hour=7),
    },
    "revogar_tokens_expirados": {
        "task": "tokens.tasks.revogar_tokens_expirados",
        "schedule": crontab(minute=0, hour=0),
    },
}

# Notificações
# Configurações de notificação – usar valores de ambiente quando definidos,
# senão definir um valor fictício para evitar ImproperlyConfigured
NOTIFICATIONS_EMAIL_API_URL = os.getenv("NOTIFICATIONS_EMAIL_API_URL", "https://stub-email.example")
NOTIFICATIONS_EMAIL_API_KEY = os.getenv("NOTIFICATIONS_EMAIL_API_KEY", "dummy-key-email")
NOTIFICATIONS_PUSH_API_URL = os.getenv("NOTIFICATIONS_PUSH_API_URL", "https://stub-push.example")
NOTIFICATIONS_PUSH_API_KEY = os.getenv("NOTIFICATIONS_PUSH_API_KEY", "dummy-key-push")
NOTIFICATIONS_WHATSAPP_API_URL = os.getenv("NOTIFICATIONS_WHATSAPP_API_URL", "https://stub-whatsapp.example")
NOTIFICATIONS_WHATSAPP_API_KEY = os.getenv("NOTIFICATIONS_WHATSAPP_API_KEY", "dummy-key-whatsapp")
NOTIFICATIONS_ENABLED = True
