"""
Django settings for Hubx project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import base64
import os
from decimal import Decimal
from pathlib import Path

import sentry_sdk
from celery.schedules import crontab
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Versão do HTMX utilizada nos templates
HTMX_VERSION = "1.9.12"

sentry_sdk.init(
    dsn=os.getenv("SENTRY_DSN"),
    integrations=[DjangoIntegration(), CeleryIntegration()],
    traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.0")),
    profiles_sample_rate=float(os.getenv("SENTRY_PROFILES_SAMPLE_RATE", "0.0")),
    environment=os.getenv("SENTRY_ENVIRONMENT", "development"),
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-f_(^m#wo6a9xfpmwi)8n7bo@k@gs!sp_(9-=jhi0%2r6o@2i^8"

# Chave para criptografia de campos sensíveis
FERNET_KEY = os.environ.get(
    "FERNET_KEY",
    base64.urlsafe_b64encode(SECRET_KEY.encode()[:32]).decode(),
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "testserver",
    "localhost",
    "127.0.0.1",
]

# Application definition

INSTALLED_APPS = [
    # ‑‑‑‑ Apps nativos do Django ‑‑‑‑
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "django_prometheus",
    # ‑‑‑‑ Terceiros (third‑party) ‑‑‑‑
    "django_ratelimit",
    "rest_framework",
    "rest_framework.authtoken",
    "widget_tweaks",
    "django_select2",
    "phonenumber_field",
    "channels",
    "simple_history",
    "silk",
    "storages",
    # ‑‑‑‑ Apps da sua solução ‑‑‑‑
    "core",
    "dashboard",
    "empresas",
    "accounts.apps.AccountsConfig",
    "organizacoes",
    "tokens.apps.TokensConfig",
    "nucleos",
    # App de eventos
    "eventos.apps.EventosConfig",
    "feed",
    "configuracoes",
    "financeiro.apps.FinanceiroConfig",
    "notificacoes.apps.NotificacoesConfig",
    "audit",
    "webhooks.apps.WebhooksConfig",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "silk.middleware.SilkyMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "accounts.middleware.ActiveUserRequiredMiddleware",
    "configuracoes.middleware.RequestInfoMiddleware",
    "configuracoes.middleware.UserLocaleMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "dashboard.middleware.DashboardTimingMiddleware",
    "audit.middleware.AuditMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
    "core.middleware.EndpointMetricsMiddleware",
]

ROOT_URLCONF = "Hubx.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.htmx_version",
                "core.context_processors.menu_items",
            ],
            # Torna os filtros/tags do widget_tweaks disponíveis globalmente
            # evitando a necessidade de `{% load widget_tweaks %}` em cada template.
            "builtins": [
                "widget_tweaks.templatetags.widget_tweaks",
                "core.templatetags.string_filters",
            ],
        },
    },
]

WSGI_APPLICATION = "Hubx.wsgi.application"
ASGI_APPLICATION = "Hubx.asgi.application"

# Channels / Redis
# Em desenvolvimento (DEBUG=True) e sem REDIS_URL definido, usa camada em memória
# para evitar dependência do Redis local e quedas de requisição.
_REDIS_URL = os.getenv("REDIS_URL") or os.getenv("CHANNEL_REDIS_URL")
_CHANNEL_LAYER_BACKEND = os.getenv("CHANNEL_LAYER_BACKEND", "").lower()
if _CHANNEL_LAYER_BACKEND in {"inmemory", "memory", "local"} or (DEBUG and not _REDIS_URL):
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            # aceita tanto tupla (host, port) quanto URL redis://
            "CONFIG": {"hosts": [_REDIS_URL or "redis://127.0.0.1:6379/0"]},
        }
    }

# Habilita/desabilita inicialização de sockets no front (templates)
# Em ambientes que iniciam com runserver (sem ASGI), defina como False para evitar 404
WEBSOCKETS_ENABLED = os.getenv("WEBSOCKETS_ENABLED", "1").strip().lower() in {"1", "true", "yes", "on"}

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "ATOMIC_REQUESTS": True,
    }
}

CACHE_URL = os.getenv("CACHE_URL")
if CACHE_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": CACHE_URL,
            "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        }
    }
else:  # pragma: no cover - fallback para testes sem Redis
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "hubx",
        }
    }

TOKENS_RATE_LIMITS = {"burst": (10, 60), "sustained": (100, 3600)}
TOKENS_RATE_LIMIT_ENABLED = True

# Configuração de webhooks para tokens
# ``TOKENS_WEBHOOK_URL`` define o endpoint que receberá eventos de criação e
# revogação de tokens. Caso não definido, nenhum webhook será enviado.
TOKENS_WEBHOOK_URL = os.getenv("TOKENS_WEBHOOK_URL")
TOKEN_WEBHOOK_SECRET = os.getenv("TOKEN_WEBHOOK_SECRET", "")

# Número de dias antes da expiração para rotacionar tokens automaticamente
TOKENS_ROTATE_BEFORE_DAYS = int(os.getenv("TOKENS_ROTATE_BEFORE_DAYS", "7"))

ONESIGNAL_APP_ID = os.getenv("ONESIGNAL_APP_ID")
ONESIGNAL_API_KEY = os.getenv("ONESIGNAL_API_KEY")
# Permite desativar OneSignal mesmo que as chaves existam.
# Valores aceitos (case-insensitive): 1/true/yes/on para ativar; 0/false/no/off para desativar.
ONESIGNAL_ENABLED = os.getenv(
    "ONESIGNAL_ENABLED",
    # padrão: ativa somente se houver chaves definidas
    "1" if (ONESIGNAL_APP_ID and ONESIGNAL_API_KEY) else "0",
).strip().lower() in {"1", "true", "yes", "on"}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "accounts.validators.ComplexPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]
# 12 rounds mantém o tempo de hash abaixo de ~300ms em máquinas modernas
BCRYPT_ROUNDS = 12

# Internationalization
LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Sao_Paulo"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
USER_MEDIA_MAX_SIZE = 50 * 1024 * 1024  # 50MB
USER_MEDIA_ALLOWED_EXTS = [".jpg", ".jpeg", ".png", ".gif", ".pdf", ".mp4", ".webm"]

ORGANIZACOES_MAX_IMAGE_SIZE = 5 * 1024 * 1024
ORGANIZACOES_ALLOWED_IMAGE_EXTENSIONS = ["jpg", "jpeg", "png"]

if os.getenv("AWS_STORAGE_BUCKET_NAME"):
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "us-east-1")
    AWS_S3_SIGNATURE_VERSION = "s3v4"
else:
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

FEED_IMAGE_ALLOWED_EXTS = [".jpg", ".jpeg", ".png", ".gif", ".webp"]
FEED_PDF_ALLOWED_EXTS = [".pdf"]
FEED_VIDEO_ALLOWED_EXTS = [".mp4", ".webm"]
FEED_IMAGE_MAX_SIZE = 5 * 1024 * 1024
FEED_PDF_MAX_SIZE = 10 * 1024 * 1024
FEED_VIDEO_MAX_SIZE = 20 * 1024 * 1024
FEED_RATE_LIMIT_POST = os.getenv("FEED_RATE_LIMIT_POST", "20/m")
FEED_RATE_LIMIT_READ = os.getenv("FEED_RATE_LIMIT_READ", "100/m")

DISCUSSAO_IMAGE_ALLOWED_EXTS = [".jpg", ".jpeg", ".png", ".gif"]
DISCUSSAO_PDF_ALLOWED_EXTS = [".pdf"]
DISCUSSAO_IMAGE_MAX_SIZE = 5 * 1024 * 1024
DISCUSSAO_PDF_MAX_SIZE = 10 * 1024 * 1024

DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = DATA_UPLOAD_MAX_MEMORY_SIZE

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "accounts.User"

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/perfil/"

AUTHENTICATION_BACKENDS = [
    "accounts.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "tokens.auth.ApiTokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "testar_notificacao": "5/minute",
    },
}

# Valores padrão para mensalidades
MENSALIDADE_ASSOCIACAO = Decimal("50.00")
MENSALIDADE_NUCLEO = Decimal("30.00")
MENSALIDADE_VENCIMENTO_DIA = 10

# Celery Beat

# Intervalo (em minutos) para execução dos plugins do feed pelo celery beat
FEED_PLUGINS_INTERVAL_MINUTES = int(os.getenv("FEED_PLUGINS_INTERVAL_MINUTES", "1"))
# Intervalo (em minutos) para rotação automática de tokens de API
TOKENS_ROTATE_INTERVAL_MINUTES = int(os.getenv("TOKENS_ROTATE_INTERVAL_MINUTES", "60"))

CELERY_BEAT_SCHEDULE = {
    "notificar_inadimplencia": {
        "task": "financeiro.tasks.inadimplencia.notificar_inadimplencia",
        "schedule": crontab(minute=0, hour=7),
    },
    "revogar_tokens_expirados": {
        "task": "tokens.tasks.revogar_tokens_expirados",
        "schedule": crontab(minute=0, hour=0),
    },
    "remover_logs_antigos": {
        "task": "tokens.tasks.remover_logs_antigos",
        "schedule": crontab(minute=0, hour=0),
    },
    "rotacionar_tokens_proximos_da_expiracao": {
        "task": "tokens.tasks.rotacionar_tokens_proximos_da_expiracao",
        "schedule": crontab(
            minute="*" if TOKENS_ROTATE_INTERVAL_MINUTES == 1 else f"*/{TOKENS_ROTATE_INTERVAL_MINUTES}"
        ),
    },
    "enviar_relatorios_diarios": {
        "task": "notificacoes.tasks.enviar_relatorios_diarios",
        "schedule": crontab(minute="*"),
    },
    "enviar_relatorios_semanais": {
        "task": "notificacoes.tasks.enviar_relatorios_semanais",
        "schedule": crontab(minute="*"),
    },
    "gerar_cobrancas_mensais": {
        "task": "financeiro.tasks.cobrancas.gerar_cobrancas_mensais",
        "schedule": crontab(minute=0, hour=0, day_of_month=1),
    },
    "expirar_solicitacoes_pendentes": {
        "task": "nucleos.tasks.expirar_solicitacoes_pendentes",
        "schedule": crontab(minute=0, hour=0),
    },
    "limpar_contadores_convites": {
        "task": "nucleos.tasks.limpar_contadores_convites",
        "schedule": crontab(minute=0, hour=0),
    },
    "expirar_convites_nucleo": {
        "task": "nucleos.tasks.expirar_convites_nucleo",
        "schedule": crontab(minute=0, hour=0),
    },
    "cleanup_audit_logs": {
        "task": "audit.tasks.cleanup_old_logs",
        "schedule": crontab(minute=0, hour=0, day_of_week="sun"),
    },
    "remover_eventos_antigos": {
        "task": "webhooks.tasks.remover_eventos_antigos",
        "schedule": crontab(minute=0, hour=0),
    },
    "executar_feed_plugins": {  # executa plugins do feed periodicamente
        "task": "feed.tasks.executar_plugins",
        "schedule": crontab(minute="*" if FEED_PLUGINS_INTERVAL_MINUTES == 1 else f"*/{FEED_PLUGINS_INTERVAL_MINUTES}"),
    },
}

CELERY_BEAT_SCHEDULE |= {
    "accounts.purge_soft_deleted_daily": {
        "task": "accounts.tasks.purge_soft_deleted",
        "schedule": crontab(minute=0, hour=3),
    }
}

# Celery - execução síncrona (modo eager) em desenvolvimento por padrão
# Evita dependência de broker (RabbitMQ/Redis) quando DEBUG=True
CELERY_TASK_ALWAYS_EAGER = os.getenv("CELERY_TASK_ALWAYS_EAGER", "1" if DEBUG else "0").lower() in {
    "1",
    "true",
    "yes",
    "on",
}
# Propaga exceções ao thread principal quando em modo eager (útil para debug)
CELERY_TASK_EAGER_PROPAGATES = True

# Notificações
# Configurações de notificação – usar valores de ambiente quando definidos,
# senão definir um valor fictício para evitar ImproperlyConfigured
NOTIFICATIONS_EMAIL_API_URL = os.getenv("NOTIFICATIONS_EMAIL_API_URL", "https://stub-email.example")
NOTIFICATIONS_EMAIL_API_KEY = os.getenv("NOTIFICATIONS_EMAIL_API_KEY", "dummy-key-email")
NOTIFICATIONS_PUSH_API_URL = os.getenv("NOTIFICATIONS_PUSH_API_URL", "https://stub-push.example")
NOTIFICATIONS_PUSH_API_KEY = os.getenv("NOTIFICATIONS_PUSH_API_KEY", "dummy-key-push")
NOTIFICATIONS_WHATSAPP_API_URL = os.getenv("NOTIFICATIONS_WHATSAPP_API_URL", "https://stub-whatsapp.example")
NOTIFICATIONS_WHATSAPP_API_KEY = os.getenv("NOTIFICATIONS_WHATSAPP_API_KEY", "dummy-key-whatsapp")
NOTIFICATIONS_ENABLED = True

DISCUSSAO_EVENTOS_BRIDGE_ENABLED = os.getenv("DISCUSSAO_EVENTOS_BRIDGE_ENABLED") in {"1", "true", "True"}

SILENCED_SYSTEM_CHECKS = ["django_ratelimit.E003", "django_ratelimit.W001"]
RATELIMIT_VIEW = "feed.api.ratelimit_exceeded"
RATELIMIT_CACHE = "default"

AUDIT_LOG_RETENTION_YEARS = int(os.getenv("AUDIT_LOG_RETENTION_YEARS", "5"))
WEBHOOK_EVENT_RETENTION_DAYS = int(os.getenv("WEBHOOK_EVENT_RETENTION_DAYS", "30"))
