# Generated by Django 5.2.2 on 2025-07-28 21:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CentroCusto",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("organizacao", "Organização"), ("nucleo", "Núcleo"), ("evento", "Evento")],
                        max_length=12,
                    ),
                ),
                ("organizacao", models.UUIDField(blank=True, null=True)),
                ("nucleo", models.UUIDField(blank=True, null=True)),
                ("evento", models.UUIDField(blank=True, null=True)),
                ("saldo", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12)),
            ],
            options={
                "verbose_name": "Centro de Custo",
                "verbose_name_plural": "Centros de Custo",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ContaAssociado",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("saldo", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12)),
            ],
            options={
                "verbose_name": "Conta do Associado",
                "verbose_name_plural": "Contas dos Associados",
                "ordering": ["user_id"],
            },
        ),
        migrations.CreateModel(
            name="LancamentoFinanceiro",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mensalidade_associacao", "Mensalidade Associação"),
                            ("mensalidade_nucleo", "Mensalidade Núcleo"),
                            ("ingresso_evento", "Ingresso Evento"),
                            ("aporte_interno", "Aporte Interno"),
                            ("aporte_externo", "Aporte Externo"),
                        ],
                        max_length=32,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_lancamento", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[("pendente", "Pendente"), ("pago", "Pago"), ("cancelado", "Cancelado")],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "centro_custo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lancamentos",
                        to="financeiro.centrocusto",
                    ),
                ),
                (
                    "conta_associado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lancamentos",
                        to="financeiro.contaassociado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lançamento Financeiro",
                "verbose_name_plural": "Lançamentos Financeiros",
                "ordering": ["-data_lancamento"],
            },
        ),
        migrations.CreateModel(
            name="Aporte",
            fields=[],
            options={
                "verbose_name": "Aporte",
                "verbose_name_plural": "Aportes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("financeiro.lancamentofinanceiro",),
        ),
    ]
