# Generated by Django 5.2.2 on 2025-08-07 18:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0019_remove_historicalmaterialdivulgacaoevento_avaliado_por_and_more"),
        ("nucleos", "0006_convitenucleo"),
        ("organizacoes", "0008_organizacaoatividadelog_organizacaochangelog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CentroCusto",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("organizacao", "Organização"), ("nucleo", "Núcleo"), ("evento", "Evento")],
                        max_length=12,
                    ),
                ),
                ("saldo", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12)),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="centros_custo",
                        to="agenda.evento",
                    ),
                ),
                (
                    "nucleo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="centros_custo",
                        to="nucleos.nucleo",
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="centros_custo",
                        to="organizacoes.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro de Custo",
                "verbose_name_plural": "Centros de Custo",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ContaAssociado",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("saldo", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contas_financeiras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta do Associado",
                "verbose_name_plural": "Contas dos Associados",
                "ordering": ["user"],
            },
        ),
        migrations.CreateModel(
            name="FinanceiroLog",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("importar", "Importar Pagamentos"),
                            ("gerar_cobranca", "Gerar Cobrança"),
                            ("repasse", "Repasse de Receita"),
                            ("editar_centro", "Editar Centro de Custo"),
                            ("editar_lancamento", "Editar Lançamento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dados_anteriores", models.JSONField(blank=True, default=dict)),
                ("dados_novos", models.JSONField(blank=True, default=dict)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Financeiro",
                "verbose_name_plural": "Logs Financeiros",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinanceiroTaskLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("nome_tarefa", models.CharField(max_length=255)),
                ("executada_em", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=20)),
                ("detalhes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Log de Tarefa Financeira",
                "verbose_name_plural": "Logs de Tarefas Financeiras",
                "ordering": ["-executada_em"],
                "indexes": [models.Index(fields=["nome_tarefa", "executada_em"], name="idx_task_nome_exec")],
            },
        ),
        migrations.CreateModel(
            name="LancamentoFinanceiro",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mensalidade_associacao", "Mensalidade Associação"),
                            ("mensalidade_nucleo", "Mensalidade Núcleo"),
                            ("ingresso_evento", "Ingresso Evento"),
                            ("aporte_interno", "Aporte Interno"),
                            ("aporte_externo", "Aporte Externo"),
                            ("despesa", "Despesa"),
                        ],
                        max_length=32,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_lancamento", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "data_vencimento",
                    models.DateTimeField(blank=True, help_text="Data limite para pagamento do lançamento", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pendente", "Pendente"), ("pago", "Pago"), ("cancelado", "Cancelado")],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("ultima_notificacao", models.DateTimeField(blank=True, null=True)),
                (
                    "centro_custo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lancamentos",
                        to="financeiro.centrocusto",
                    ),
                ),
                (
                    "conta_associado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lancamentos",
                        to="financeiro.contaassociado",
                    ),
                ),
                (
                    "originador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aportes_lancados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lançamento Financeiro",
                "verbose_name_plural": "Lançamentos Financeiros",
                "ordering": ["-data_lancamento"],
            },
        ),
        migrations.CreateModel(
            name="Aporte",
            fields=[],
            options={
                "verbose_name": "Aporte",
                "verbose_name_plural": "Aportes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("financeiro.lancamentofinanceiro",),
        ),
        migrations.CreateModel(
            name="ImportacaoPagamentos",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("arquivo", models.CharField(max_length=255)),
                ("data_importacao", models.DateTimeField(default=django.utils.timezone.now)),
                ("total_processado", models.PositiveIntegerField(default=0)),
                ("erros", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("processando", "Em processamento"), ("concluido", "Concluído"), ("erro", "Erro")],
                        default="processando",
                        max_length=20,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Importação de Pagamentos",
                "verbose_name_plural": "Importações de Pagamentos",
                "ordering": ["-data_importacao"],
                "indexes": [models.Index(fields=["data_importacao"], name="idx_importacao_data")],
            },
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["centro_custo", "conta_associado"], name="idx_centro_conta"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["centro_custo"], name="idx_lanc_centro"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["conta_associado"], name="idx_lanc_conta"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["data_lancamento"], name="idx_lanc_dt_lanc"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["data_vencimento"], name="idx_lanc_dt_venc"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["status"], name="idx_lanc_status"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(
                fields=["centro_custo", "conta_associado", "tipo", "valor", "data_lancamento"],
                name="idx_lanc_duplicidade",
            ),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(
                fields=["centro_custo", "conta_associado", "status", "data_vencimento"], name="idx_lanc_cc_status_venc"
            ),
        ),
    ]
