# Generated by Django 5.2.2 on 2025-07-28 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0005_briefingevento_avaliado_em_and_more"),
        ("financeiro", "0001_initial"),
        ("nucleos", "0002_nucleo_deleted_nucleo_deleted_at_and_more"),
        ("organizacoes", "0003_alter_organizacao_options_organizacao_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contaassociado",
            options={
                "ordering": ["user"],
                "verbose_name": "Conta do Associado",
                "verbose_name_plural": "Contas dos Associados",
            },
        ),
        migrations.RemoveField(
            model_name="contaassociado",
            name="user_id",
        ),
        migrations.AddField(
            model_name="contaassociado",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contas_financeiras",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="data_vencimento",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="centrocusto",
            name="evento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="centros_custo",
                to="agenda.evento",
            ),
        ),
        migrations.AlterField(
            model_name="centrocusto",
            name="nucleo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="centros_custo",
                to="nucleos.nucleo",
            ),
        ),
        migrations.AlterField(
            model_name="centrocusto",
            name="organizacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="centros_custo",
                to="organizacoes.organizacao",
            ),
        ),
    ]
