# Generated by Django 5.2.2 on 2025-08-08 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0002_integracoes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integracaoconfig",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
