# Generated by Django 5.2.2 on 2025-07-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0002_alter_contaassociado_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lancamentofinanceiro",
            name="data_vencimento",
            field=models.DateTimeField(blank=True, help_text="Data limite para pagamento do lançamento", null=True),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["centro_custo", "conta_associado"], name="idx_centro_conta"),
        ),
    ]
