# Generated by Django 5.2.5 on 2025-08-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0002_integracaoidempotency_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integracaoconfig",
            name="ativo",
        ),
    ]
