# Generated by Django 5.2.5 on 2025-08-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0003_remove_integracaoconfig_ativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="integracaoconfig",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="integracaoconfig",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
