# Generated by Django 5.2.2 on 2025-07-29 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0003_add_index_lancamento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="originador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aportes_lancados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
