# Generated by Django 5.2.5 on 2025-08-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0004_integracaoconfig_deleted_integracaoconfig_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="origem",
            field=models.CharField(
                choices=[("manual", "Manual"), ("importacao", "Importação")], default="manual", max_length=20
            ),
        ),
    ]
