# Generated by Django 5.2.2 on 2025-07-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0004_add_originador_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="ultima_notificacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
