# Generated by Django 5.2.2 on 2025-07-29 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0005_lancamentofinanceiro_ultima_notificacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["centro_custo"], name="idx_lanc_centro"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["conta_associado"], name="idx_lanc_conta"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["data_lancamento"], name="idx_lanc_dt_lanc"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["data_vencimento"], name="idx_lanc_dt_venc"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["status"], name="idx_lanc_status"),
        ),
    ]
