# Generated by Django 5.2.5 on 2025-08-18 21:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0005_lancamentofinanceiro_origem"),
    ]

    operations = [
        migrations.AddField(
            model_name="importacaopagamentos",
            name="idempotency_key",
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
