# Generated by Django 5.2.5 on 2025-08-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0006_importacaopagamentos_idempotency_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lancamentofinanceiro",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("mensalidade_associacao", "Mensalidade Associação"),
                    ("mensalidade_nucleo", "Mensalidade Núcleo"),
                    ("ingresso_evento", "Ingresso Evento"),
                    ("aporte_interno", "Aporte Interno"),
                    ("aporte_externo", "Aporte Externo"),
                    ("despesa", "Despesa"),
                    ("ajuste", "Ajuste"),
                    ("repasse", "Repasse de Receita"),
                ],
                max_length=32,
            ),
        ),
    ]
