# Generated by Django 5.2.2 on 2025-08-01 16:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0006_add_extra_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportacaoPagamentos",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("arquivo", models.CharField(max_length=255)),
                ("data_importacao", models.DateTimeField(default=django.utils.timezone.now)),
                ("total_processado", models.PositiveIntegerField(default=0)),
                ("erros", models.JSONField(blank=True, default=list)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Importação de Pagamentos",
                "verbose_name_plural": "Importações de Pagamentos",
                "ordering": ["-data_importacao"],
            },
        ),
    ]
