# Generated by Django 5.2.5 on 2025-08-21 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0007_alter_lancamentofinanceiro_tipo"),
        ("organizacoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="integracaoconfig",
            name="organizacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integracoes",
                to="organizacoes.organizacao",
            ),
        ),
        migrations.AddField(
            model_name="integracaoconfig",
            name="autenticacao",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
