# Generated by Django 5.2.2 on 2025-08-04 18:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0007_importacaopagamentos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceiroLog",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("importar", "Importar Pagamentos"),
                            ("gerar_cobranca", "Gerar Cobrança"),
                            ("repasse", "Repasse de Receita"),
                            ("editar_centro", "Editar Centro de Custo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dados_anteriores", models.JSONField(blank=True, default=dict)),
                ("dados_novos", models.JSONField(blank=True, default=dict)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Financeiro",
                "verbose_name_plural": "Logs Financeiros",
                "ordering": ["-created_at"],
            },
        ),
    ]
