# Generated by Django 5.2.5 on 2025-08-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0007_alter_lancamentofinanceiro_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="centrocusto",
            name="descricao",
            field=models.TextField(blank=True),
        ),
    ]
