# Generated by Django 5.2.2 on 2025-08-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0008_financeirolog"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceiroTaskLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_tarefa", models.CharField(max_length=255)),
                ("executada_em", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=20)),
                ("detalhes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Log de Tarefa Financeira",
                "verbose_name_plural": "Logs de Tarefas Financeiras",
                "ordering": ["-executada_em"],
            },
        ),
    ]
