# Generated by Django 5.2.5 on 2025-08-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0008_centrocusto_descricao"),
        ("financeiro", "0008_integracaoconfig_new_fields"),
    ]

    operations = []
