# Generated by Django 5.2.5 on 2025-09-22 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0009_merge_20250821_1829"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integracaoconfig",
            name="organizacao",
        ),
        migrations.DeleteModel(
            name="IntegracaoIdempotency",
        ),
        migrations.DeleteModel(
            name="IntegracaoLog",
        ),
        migrations.DeleteModel(
            name="IntegracaoConfig",
        ),
    ]
