# Generated by Django 5.2.5 on 2025-09-23 14:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0010_remove_integracaoconfig_organizacao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carteira",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("operacional", "Operacional"),
                            ("reserva", "Reserva"),
                            ("investimento", "Investimento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("saldo", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12)),
                (
                    "centro_custo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carteiras",
                        to="financeiro.centrocusto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carteira",
                "verbose_name_plural": "Carteiras",
                "ordering": ["nome"],
                "indexes": [
                    models.Index(fields=["centro_custo"], name="idx_carteira_centro"),
                    models.Index(fields=["tipo"], name="idx_carteira_tipo"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("centro_custo", "tipo"), name="uniq_carteira_centro_tipo")
                ],
            },
        ),
    ]
