# Generated by Django 5.2.5 on 2025-09-23 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0011_carteira"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="carteira",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lancamentos",
                to="financeiro.carteira",
            ),
        ),
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="carteira_contraparte",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lancamentos_contraparte",
                to="financeiro.carteira",
            ),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["carteira", "status", "data_vencimento"], name="idx_lanc_cart_status_venc"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=["carteira_contraparte"], name="idx_lanc_cart_contra"),
        ),
    ]
