# Generated by Django 5.2.5 on 2025-09-23 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0012_lancamentofinanceiro_carteira_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carteira",
            name="conta_associado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carteiras",
                to="financeiro.contaassociado",
            ),
        ),
        migrations.AlterField(
            model_name="carteira",
            name="centro_custo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carteiras",
                to="financeiro.centrocusto",
            ),
        ),
        migrations.AddIndex(
            model_name="carteira",
            index=models.Index(fields=["conta_associado"], name="idx_carteira_conta"),
        ),
        migrations.AddConstraint(
            model_name="carteira",
            constraint=models.UniqueConstraint(fields=("conta_associado", "tipo"), name="uniq_carteira_conta_tipo"),
        ),
        migrations.AddConstraint(
            model_name="carteira",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("centro_custo__isnull", False), ("conta_associado__isnull", True)),
                    models.Q(("centro_custo__isnull", True), ("conta_associado__isnull", False)),
                    _connector="OR",
                ),
                name="carteira_single_owner",
            ),
        ),
    ]
