# Generated by Django 5.2.2 on 2025-08-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0013_importacaopagamentos_status"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="lancamentofinanceiro",
            new_name="idx_lanc_cc_status_venc",
            old_name="idx_lanc_centro_conta_status_venc",
        ),
    ]
