# Generated by Django 5.2.2 on 2025-08-07 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0013_importacaopagamentos_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="lancamentofinanceiro",
            new_name="idx_lanc_cc_status_venc",
            old_name="idx_lanc_centro_conta_status_venc",
        ),
        migrations.AlterField(
            model_name="financeirolog",
            name="acao",
            field=models.CharField(
                choices=[
                    ("importar", "Importar Pagamentos"),
                    ("gerar_cobranca", "Gerar Cobrança"),
                    ("repasse", "Repasse de Receita"),
                    ("editar_centro", "Editar Centro de Custo"),
                    ("editar_lancamento", "Editar Lançamento"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="importacaopagamentos",
            index=models.Index(fields=["data_importacao"], name="idx_importacao_data"),
        ),
    ]
