# Generated by Django 5.2.2 on 2025-08-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0014_rename_idx_lanc_centro_conta_status_venc_idx_lanc_cc_status_venc"),
        ("financeiro", "0014_rename_idx_lanc_centro_conta_status_venc_idx_lanc_cc_status_venc_and_more"),
    ]

    operations = []
