# Generated by Django 5.2.5 on 2025-09-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0014_backfill_principal_carteiras"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contaassociado",
            options={
                "managed": False,
                "ordering": ["user"],
                "verbose_name": "Conta do Associado",
                "verbose_name_plural": "Contas dos Associados",
            },
        ),
        migrations.RemoveField(
            model_name="centrocusto",
            name="saldo",
        ),
    ]
