# Generated by Django 5.2.5 on 2025-09-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0015_alter_contaassociado_options"),
        ("financeiro", "0015_alter_contaassociado_options_and_more"),
    ]

    operations = []
