# Generated by Django 5.2.5 on 2025-08-08 18:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0001_initial"),
        ("nucleos", "0001_initial"),
        ("organizacoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="FeedPluginConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("module_path", models.CharField(max_length=255)),
                ("frequency", models.PositiveIntegerField(default=0)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_plugins",
                        to="organizacoes.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Plugin",
                "verbose_name_plural": "Configurações de Plugins",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "tipo_feed",
                    models.CharField(
                        choices=[
                            ("global", "Feed Global"),
                            ("usuario", "Mural do Usuário"),
                            ("nucleo", "Feed do Núcleo"),
                            ("evento", "Feed do Evento"),
                        ],
                        default="global",
                        max_length=10,
                    ),
                ),
                ("conteudo", models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ("image", models.ImageField(blank=True, null=True, upload_to="uploads/")),
                ("pdf", models.FileField(blank=True, null=True, upload_to="uploads/")),
                ("video", models.FileField(blank=True, null=True, upload_to="videos/")),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="posts", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="agenda.evento"
                    ),
                ),
                (
                    "nucleo",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="nucleos.nucleo"
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="posts", to="organizacoes.organizacao"
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, related_name="posts", to="feed.tag")),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModeracaoPost",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("pendente", "Pendente"), ("aprovado", "Aprovado"), ("rejeitado", "Rejeitado")],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("motivo", models.TextField(blank=True)),
                ("avaliado_em", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "avaliado_por",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="moderacao", to="feed.post"
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderação de Post",
                "verbose_name_plural": "Moderações de Posts",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("texto", models.TextField()),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="feed.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="feed.post"
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário",
                "verbose_name_plural": "Comentários",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostView",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="visualizacoes", to="feed.post"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visualizacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Visualização de Post",
                "verbose_name_plural": "Visualizações de Posts",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="likes", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="feed.post"
                    ),
                ),
            ],
            options={
                "verbose_name": "Curtida",
                "verbose_name_plural": "Curtidas",
                "unique_together": {("post", "user")},
            },
        ),
        migrations.CreateModel(
            name="Flag",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="flags", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="flags", to="feed.post"
                    ),
                ),
            ],
            options={
                "verbose_name": "Denúncia",
                "verbose_name_plural": "Denúncias",
                "unique_together": {("post", "user")},
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="bookmarks", to="feed.post"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bookmark",
                "verbose_name_plural": "Bookmarks",
                "unique_together": {("user", "post")},
            },
        ),
        migrations.CreateModel(
            name="Reacao",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("vote", models.CharField(choices=[("like", "Curtida"), ("share", "Compartilhamento")], max_length=20)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reacoes", to="feed.post"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reacoes", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Reação",
                "verbose_name_plural": "Reações",
                "unique_together": {("post", "user", "vote")},
            },
        ),
    ]
