# Generated by Django 5.2.4 on 2025-07-15 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nucleos", "0001_initial"),
        ("organizacoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("conteudo", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="uploads/")),
                ("pdf", models.FileField(blank=True, null=True, upload_to="uploads/")),
                ("publico", models.BooleanField(default=True)),
                (
                    "tipo_feed",
                    models.CharField(
                        choices=[("publico", "Público"), ("nucleo", "Núcleo")], default="publico", max_length=10
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="posts", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "nucleo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postagens",
                        to="nucleos.nucleo",
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        db_column="organization",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="organizacoes.organizacao",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
    ]
