# Generated by Django 5.2.2 on 2025-07-10 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
        ("nucleos", "0002_nucleo_created_at_nucleo_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="imagem",
        ),
        migrations.RemoveField(
            model_name="post",
            name="visibilidade",
        ),
        migrations.AddField(
            model_name="post",
            name="media",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="feed/media/%Y/%m/",
                verbose_name="Mídia",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="nucleo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="nucleos.nucleo",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tipo_feed",
            field=models.CharField(
                choices=[("publico", "Público"), ("nucleo", "Núcleo")],
                default="publico",
                max_length=10,
            ),
        ),
    ]
