# Generated by Django 5.2.2 on 2025-08-07 23:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
        ("organizacoes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedPluginConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("module_path", models.CharField(max_length=255)),
                ("frequency", models.PositiveIntegerField(default=0)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_plugins",
                        to="organizacoes.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Plugin",
                "verbose_name_plural": "Configurações de Plugins",
            },
        ),
    ]
