# Generated by Django 5.2.5 on 2025-08-14 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_alter_bookmark_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="flag",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="flag",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="flag",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="flag",
            unique_together={("post", "user", "deleted")},
        ),
    ]
