# Generated by Django 5.2.2 on 2025-07-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_remove_post_imagem_remove_post_visibilidade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="publico",
            field=models.BooleanField(default=True),
        ),
    ]
