# Generated by Django 5.2.5 on 2025-08-14 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0003_alter_flag_unique_together_flag_deleted_and_more"),
    ]

    # This migration became a no-op after merging parallel branches that
    # introduced the same soft delete fields. The actual field additions
    # live in ``0004_tag_deleted_tag_deleted_at_alter_tag_nome_and_more``.
    # Keeping the empty migration preserves historical numbering while
    # avoiding duplicate column errors during migration setup.
    operations = []
