# Generated by Django 5.2.2 on 2025-07-10 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_add_publico_field"),
        ("nucleos", "0002_nucleo_created_at_nucleo_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="nucleo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="postagens",
                to="nucleos.nucleo",
            ),
        ),
    ]
