# Generated by Django 5.2.5 on 2025-08-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_alter_flag_unique_together_flag_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
