# Generated by Django 5.2.2 on 2025-07-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0004_alter_post_nucleo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="media",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="post",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
