# Generated by Django 5.2.2 on 2025-08-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0004_post_deleted_alter_comment_id_alter_like_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
