# Generated by Django 5.2.5 on 2025-08-14 22:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0004_tag_deleted_tag_deleted_at"),
        ("feed", "0004_tag_deleted_tag_deleted_at_alter_tag_nome_and_more"),
    ]

    operations = []
