# Generated by Django 5.2.5 on 2025-08-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0005_merge_20250814_1958"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video_preview",
            field=models.ImageField(blank=True, null=True, upload_to="video_previews/"),
        ),
    ]
