# Generated by Django 5.2.2 on 2025-08-04 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0005_post_deleted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderacaopost",
            name="avaliado_em",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="moderacaopost",
            name="avaliado_por",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="moderacaopost",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="moderacao", to="feed.post"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
