# Generated by Django 5.2.5 on 2025-08-18 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0005_merge_20250814_1958"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderacaopost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="moderacoes", to="feed.post"
            ),
        ),
    ]
