# Generated by Django 5.2.5 on 2025-08-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0006_alter_moderacaopost_post"),
        ("feed", "0006_post_video_preview"),
    ]

    operations = []
