# Generated by Django 5.2.2 on 2025-08-06 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0007_remove_post_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="conteudo",
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
