# Generated by Django 5.2.5 on 2025-08-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0007_merge_20250818_1737"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedpluginconfig",
            name="last_run",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
