# Generated by Django 5.2.5 on 2025-08-23 19:46

import django.utils.timezone
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0008_feedpluginconfig_last_run"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task_id", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
