# Generated by Django 5.2.5 on 2025-08-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0008_feedpluginconfig_last_run"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Like",
        ),
    ]
