# Generated by Django 5.2.5 on 2025-08-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0009_delete_like"),
        ("feed", "0009_pendingupload"),
    ]

    operations = []
