# Generated by Django 5.2.5 on 2025-11-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0010_merge_0009_delete_like_0009_pendingupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="link_preview",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
