# Generated by Django 5.2.2 on 2025-08-07 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0011_bookmark"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="post_conteudo_gin",
        ),
        migrations.RemoveIndex(
            model_name="tag",
            name="tag_nome_gin",
        ),
        migrations.AlterField(
            model_name="flag",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
