from django.urls import path

from .views import (
    CategoriaCreateView,
    CategoriaDeleteView,
    CategoriaListView,
    CategoriaUpdateView,
    DenunciaApproveView,
    DenunciaDetailView,
    DenunciaListView,
    DenunciaRejectView,
    DenunciaRemoveContentView,
    InteracaoView,
    RespostaCreateView,
    RespostaDetailView,
    RespostaDeleteView,
    RespostaUpdateView,
    TagCreateView,
    TagDeleteView,
    TagListView,
    TagUpdateView,
    TopicoCreateView,
    TopicoDeleteView,
    TopicoDetailView,
    TopicoListView,
    TopicoMarkResolvedView,
    TopicoToggleFechadoView,
    TopicoUpdateView,
)
from core.permissions import no_superadmin_required

urlpatterns = [
    path("", no_superadmin_required(CategoriaListView.as_view()), name="categorias"),
    path("tags/", no_superadmin_required(TagListView.as_view()), name="tags"),
    path("tags/novo/", no_superadmin_required(TagCreateView.as_view()), name="tag_criar"),
    path("tags/<slug:slug>/editar/", no_superadmin_required(TagUpdateView.as_view()), name="tag_editar"),
    path("tags/<slug:slug>/remover/", no_superadmin_required(TagDeleteView.as_view()), name="tag_remover"),
    path("denuncias/<str:status>/", no_superadmin_required(DenunciaListView.as_view()), name="denuncia_list"),
    path("denuncias/<uuid:pk>/", no_superadmin_required(DenunciaDetailView.as_view()), name="denuncia_detalhe"),
    path("denuncias/<uuid:pk>/aprovar/", no_superadmin_required(DenunciaApproveView.as_view()), name="denuncia_aprovar"),
    path("denuncias/<uuid:pk>/rejeitar/", no_superadmin_required(DenunciaRejectView.as_view()), name="denuncia_rejeitar"),
    path("denuncias/<uuid:pk>/remover/", no_superadmin_required(DenunciaRemoveContentView.as_view()), name="denuncia_remover"),
    path("categorias/novo/", no_superadmin_required(CategoriaCreateView.as_view()), name="categoria_criar"),
    path("categorias/<slug:slug>/editar/", no_superadmin_required(CategoriaUpdateView.as_view()), name="categoria_editar"),
    path("categorias/<slug:slug>/remover/", no_superadmin_required(CategoriaDeleteView.as_view()), name="categoria_remover"),
    path(
        "comentario/<int:pk>/",
        no_superadmin_required(RespostaDetailView.as_view()),
        name="resposta_detalhe",
    ),
    path(
        "comentario/<int:pk>/editar/",
        no_superadmin_required(RespostaUpdateView.as_view()),
        name="resposta_editar",
    ),
    path(
        "comentario/<int:pk>/remover/",
        no_superadmin_required(RespostaDeleteView.as_view()),
        name="delete_comment",
    ),
    path("<slug:categoria_slug>/", no_superadmin_required(TopicoListView.as_view()), name="topicos"),
    path("<slug:categoria_slug>/novo/", no_superadmin_required(TopicoCreateView.as_view()), name="topico_criar"),
    path(
        "<slug:categoria_slug>/<slug:topico_slug>/",
        no_superadmin_required(TopicoDetailView.as_view()),
        name="topico_detalhe",
    ),
    path(
        "<slug:categoria_slug>/<slug:topico_slug>/editar/",
        no_superadmin_required(TopicoUpdateView.as_view()),
        name="topico_editar",
    ),
    path(
        "<slug:categoria_slug>/<slug:topico_slug>/remover/",
        no_superadmin_required(TopicoDeleteView.as_view()),
        name="topico_remover",
    ),
    path(
        "<slug:categoria_slug>/<slug:topico_slug>/responder/",
        no_superadmin_required(RespostaCreateView.as_view()),
        name="resposta_criar",
    ),
    path(
        "<slug:categoria_slug>/<slug:topico_slug>/resolver/",
        no_superadmin_required(TopicoMarkResolvedView.as_view()),
        name="topico_resolver",
    ),
    path(
        "<slug:categoria_slug>/<slug:topico_slug>/toggle-fechado/",
        no_superadmin_required(TopicoToggleFechadoView.as_view()),
        name="topico_toggle_fechado",
    ),
    path(
        "interacao/<int:content_type_id>/<int:object_id>/<str:acao>/",
        no_superadmin_required(InteracaoView.as_view()),
        name="interacao",
    ),
]
