# Generated by Django 5.2.5 on 2025-08-08 18:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizacao",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                ("descricao", models.TextField(blank=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[("ong", "ONG"), ("empresa", "Empresa"), ("coletivo", "Coletivo")],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("rua", models.CharField(blank=True, max_length=255, verbose_name="Rua")),
                ("cidade", models.CharField(blank=True, max_length=100, verbose_name="Cidade")),
                ("estado", models.CharField(blank=True, max_length=50, verbose_name="Estado")),
                ("contato_nome", models.CharField(blank=True, max_length=255, verbose_name="Contato principal")),
                ("contato_email", models.EmailField(blank=True, max_length=254, verbose_name="Email do contato")),
                ("contato_telefone", models.CharField(blank=True, max_length=20, verbose_name="Telefone do contato")),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="organizacoes/avatars/")),
                ("cover", models.ImageField(blank=True, null=True, upload_to="organizacoes/capas/")),
                ("rate_limit_multiplier", models.FloatField(default=1)),
                ("inativa", models.BooleanField(default=False)),
                ("inativada_em", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organizacoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organização",
                "verbose_name_plural": "Organizações",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="OrganizacaoAtividadeLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("acao", models.CharField(max_length=50)),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("detalhes", models.TextField(blank=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atividade_logs",
                        to="organizacoes.organizacao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="OrganizacaoChangeLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("campo_alterado", models.CharField(max_length=100)),
                ("valor_antigo", models.TextField(blank=True, null=True)),
                ("valor_novo", models.TextField(blank=True, null=True)),
                ("alterado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "alterado_por",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="organizacoes.organizacao",
                    ),
                ),
            ],
            options={
                "ordering": ["-alterado_em"],
            },
        ),
    ]
