# Generated by Django 5.2.2 on 2025-07-15 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organizacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                ("descricao", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="organizacoes/logos/")),
            ],
            options={
                "verbose_name": "Organização",
                "verbose_name_plural": "Organizações",
            },
        ),
    ]
