# Generated by Django 5.2.2 on 2025-06-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                ("descricao", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="organizacoes/logos/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Organização",
                "verbose_name_plural": "Organizações",
            },
        ),
    ]
