# Generated by Django 5.2.2 on 2025-07-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "populate_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizacao",
            name="logo",
        ),
        migrations.AddField(
            model_name="organizacao",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="organizacoes/avatars/"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="organizacoes/capas/"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
