# Generated by Django 5.2.2 on 2025-08-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacao",
            name="rate_limit_multiplier",
            field=models.FloatField(default=1),
        ),
    ]
