# Generated by Django 5.2.2 on 2025-07-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0001_remove_organizacao_logo_organizacao_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizacao",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
