# Generated by Django 5.2.2 on 2025-07-25 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0002_alter_organizacao_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizacao",
            options={"ordering": ["nome"], "verbose_name": "Organização", "verbose_name_plural": "Organizações"},
        ),
        migrations.AddField(
            model_name="organizacao",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="inativa",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="inativada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="OrganizacaoLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("acao", models.CharField(max_length=50)),
                ("dados_antigos", models.JSONField(blank=True, default=dict)),
                ("dados_novos", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="organizacoes.organizacao"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
