# Generated by Django 5.2.5 on 2025-08-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0002_alter_organizacaoatividadelog_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizacao",
            name="inativa",
        ),
        migrations.RemoveField(
            model_name="organizacao",
            name="inativada_em",
        ),
    ]
