# Generated by Django 5.2.2 on 2025-07-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0003_alter_organizacao_options_organizacao_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacao",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="contato_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email do contato"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="contato_nome",
            field=models.CharField(blank=True, max_length=255, verbose_name="Contato principal"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="contato_telefone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefone do contato"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="estado",
            field=models.CharField(blank=True, max_length=50, verbose_name="Estado"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="rua",
            field=models.CharField(blank=True, max_length=255, verbose_name="Rua"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[("ong", "ONG"), ("empresa", "Empresa"), ("coletivo", "Coletivo")],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
