# Generated by Django 5.2.5 on 2025-08-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0004_organizacao_indice_reajuste"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacaoatividadelog",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organizacaoatividadelog",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizacaochangelog",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organizacaochangelog",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
