# Generated by Django 5.2.5 on 2025-08-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0004_organizacao_indice_reajuste"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacao",
            name="inativa",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="inativada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
