# Generated by Django 5.2.5 on 2025-08-18 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0005_organizacao_inativa_organizacao_inativada_em"),
        ("organizacoes", "0005_organizacaoatividadelog_deleted_and_more"),
    ]

    operations = []
