# Generated by Django 5.2.2 on 2025-08-04 18:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0006_alter_organizacaolog_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizacaolog",
            options={"get_latest_by": "created_at", "ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="organizacaolog",
            old_name="dados_antigos",
            new_name="dados_anteriores",
        ),
        migrations.RemoveField(
            model_name="organizacaolog",
            name="created",
        ),
        migrations.RemoveField(
            model_name="organizacaolog",
            name="modified",
        ),
        migrations.AddField(
            model_name="organizacaolog",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="organizacaolog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="organizacao",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
