# Generated by Django 5.2.5 on 2025-08-22 18:45

from django.db import migrations, models
import json


def _convert_empty_strings(apps, schema_editor):
    Log = apps.get_model("organizacoes", "OrganizacaoAtividadeLog")
    for log in Log.objects.filter(detalhes=""):
        log.detalhes = "{}"
        log.save(update_fields=["detalhes"])


def _load_json(apps, schema_editor):
    Log = apps.get_model("organizacoes", "OrganizacaoAtividadeLog")
    for log in Log.objects.all():
        if isinstance(log.detalhes, str):
            try:
                log.detalhes = json.loads(log.detalhes) if log.detalhes else {}
            except json.JSONDecodeError:
                log.detalhes = {}
            log.save(update_fields=["detalhes"])


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0007_organizacaorecurso"),
    ]

    operations = [
        migrations.RunPython(_convert_empty_strings, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="organizacaoatividadelog",
            name="detalhes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(_load_json, migrations.RunPython.noop),
    ]
