# Generated by Django 5.2.2 on 2025-08-04 23:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0007_alter_organizacaolog_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizacaoAtividadeLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("acao", models.CharField(max_length=50)),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("detalhes", models.TextField(blank=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atividade_logs",
                        to="organizacoes.organizacao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="OrganizacaoChangeLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("campo_alterado", models.CharField(max_length=100)),
                ("valor_antigo", models.TextField(blank=True, null=True)),
                ("valor_novo", models.TextField(blank=True, null=True)),
                ("alterado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "alterado_por",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="organizacoes.organizacao",
                    ),
                ),
            ],
            options={
                "ordering": ["-alterado_em"],
            },
        ),
        migrations.DeleteModel(
            name="OrganizacaoLog",
        ),
    ]
