# Generated by Django 5.2.5 on 2025-10-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0008_alter_organizacaoatividadelog_detalhes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizacao",
            name="indice_reajuste",
        ),
    ]
