# Generated by Django 5.2.5 on 2025-11-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0009_remove_organizacao_indice_reajuste"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacao",
            name="chave_pix",
            field=models.CharField(blank=True, max_length=255, verbose_name="Chave Pix"),
        ),
    ]
