# Generated by Django 5.2.5 on 2025-11-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0011_remove_organizacao_slug_and_rate_limit_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacao",
            name="feed_noticias",
            field=models.URLField(blank=True, verbose_name="Feed de notícias"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="icone_site",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="organizacoes/icones/",
                verbose_name="Ícone do site",
            ),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="site",
            field=models.URLField(blank=True, verbose_name="Site"),
        ),
    ]
