# Generated by Django 5.2.5 on 2025-11-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0012_organizacao_feed_noticias_organizacao_icone_site_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacao",
            name="nome_site",
            field=models.CharField(blank=True, max_length=12, verbose_name="Nome do site"),
        ),
    ]
