# Generated by Django 5.2.5 on 2025-11-19 19:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0013_organizacao_nome_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizacaoFeedSync",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("external_id", models.CharField(max_length=512)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("link", models.URLField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feeds_sincronizados",
                        to="organizacoes.organizacao",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("organizacao", "external_id")},
            },
        ),
    ]
