# Generated by Django 5.2.5 on 2025-11-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0014_organizacaofeedsync"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacao",
            name="agencia",
            field=models.CharField(blank=True, max_length=10, verbose_name="Agência"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="codigo_banco",
            field=models.CharField(blank=True, max_length=10, verbose_name="Código do banco"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="conta_corrente",
            field=models.CharField(blank=True, max_length=20, verbose_name="Conta corrente"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="nome_banco",
            field=models.CharField(blank=True, max_length=255, verbose_name="Nome do banco"),
        ),
    ]
