# Generated by Django 5.2.5 on 2025-11-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0015_organizacao_dados_bancarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacao",
            name="mercado_pago_access_token",
            field=models.CharField(blank=True, max_length=255, verbose_name="Access token do Mercado Pago"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="mercado_pago_public_key",
            field=models.CharField(blank=True, max_length=255, verbose_name="Public key do Mercado Pago"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="mercado_pago_webhook_secret",
            field=models.CharField(blank=True, max_length=255, verbose_name="Segredo do webhook do Mercado Pago"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="paypal_client_id",
            field=models.CharField(blank=True, max_length=255, verbose_name="Client ID do PayPal"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="paypal_client_secret",
            field=models.CharField(blank=True, max_length=255, verbose_name="Client secret do PayPal"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="paypal_currency",
            field=models.CharField(blank=True, default="BRL", max_length=10, verbose_name="Moeda padrão do PayPal"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="paypal_webhook_secret",
            field=models.CharField(blank=True, max_length=255, verbose_name="Segredo do webhook do PayPal"),
        ),
    ]
