# Generated by Django 5.2.5 on 2025-11-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0016_organizacao_mercado_pago_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacao",
            name="cep",
            field=models.CharField(blank=True, max_length=10, verbose_name="CEP"),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="contato_whatsapp",
            field=models.CharField(blank=True, max_length=20, verbose_name="WhatsApp"),
        ),
        migrations.RemoveField(
            model_name="organizacao",
            name="cover",
        ),
    ]
