# Generated by Django 5.2.5 on 2026-01-14 13:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0017_organizacao_cep_contato_whatsapp_remove_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacao",
            name="dia_vencimento",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)],
                verbose_name="Dia de vencimento",
            ),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="periodicidade",
            field=models.CharField(
                choices=[
                    ("mensal", "Mensal"),
                    ("trimestral", "Trimestral"),
                    ("semestral", "Semestral"),
                    ("anual", "Anual"),
                ],
                default="mensal",
                max_length=20,
                verbose_name="Periodicidade",
            ),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="valor_associacao",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("50.00"), max_digits=8, verbose_name="Valor de associação"
            ),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="valor_nucleacao",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("30.00"), max_digits=8, verbose_name="Valor de nucleação"
            ),
        ),
    ]
