# Generated by Django 5.2.5 on 2025-08-08 18:44

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("codigo", models.SlugField(unique=True, verbose_name="Código")),
                ("assunto", models.CharField(max_length=200, verbose_name="Assunto")),
                ("corpo", models.TextField(verbose_name="Corpo")),
                (
                    "canal",
                    models.CharField(
                        choices=[("email", "E-mail"), ("push", "Push"), ("whatsapp", "WhatsApp"), ("todos", "Todos")],
                        max_length=20,
                        verbose_name="Canal",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Template de Notificação",
                "verbose_name_plural": "Templates de Notificação",
                "permissions": [("can_send_notifications", "Can send notifications")],
            },
        ),
        migrations.CreateModel(
            name="HistoricoNotificacao",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "canal",
                    models.CharField(
                        choices=[("email", "E-mail"), ("push", "Push"), ("whatsapp", "WhatsApp"), ("todos", "Todos")],
                        max_length=20,
                    ),
                ),
                ("conteudo", models.JSONField(default=list)),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Histórico de Notificação",
                "verbose_name_plural": "Históricos de Notificação",
                "ordering": ["-enviado_em"],
                "unique_together": {("user", "canal", "enviado_em")},
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("destinatario", models.CharField(blank=True, max_length=254)),
                (
                    "canal",
                    models.CharField(
                        choices=[("email", "E-mail"), ("push", "Push"), ("whatsapp", "WhatsApp"), ("todos", "Todos")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("enviada", "Enviada"),
                            ("falha", "Falha"),
                            ("lida", "Lida"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("data_envio", models.DateTimeField(blank=True, null=True)),
                ("erro", models.TextField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="notificacoes.notificationtemplate"
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Notificação",
                "verbose_name_plural": "Logs de Notificação",
                "unique_together": {("user", "template", "canal", "created")},
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("device_id", models.CharField(max_length=255)),
                ("endpoint", models.CharField(max_length=500)),
                ("p256dh", models.CharField(max_length=255)),
                ("auth", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscrição Push",
                "verbose_name_plural": "Inscrições Push",
                "unique_together": {("user", "device_id")},
            },
        ),
    ]
