# Generated by Django 5.2.2 on 2025-07-29 20:51

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.SlugField(unique=True)),
                ("assunto", models.CharField(max_length=200)),
                ("corpo", models.TextField()),
                (
                    "canal",
                    models.CharField(
                        choices=[("email", "E-mail"), ("push", "Push"), ("whatsapp", "WhatsApp"), ("todos", "Todos")],
                        max_length=20,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Template de Notificação",
                "verbose_name_plural": "Templates de Notificação",
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[("email", "E-mail"), ("push", "Push"), ("whatsapp", "WhatsApp"), ("todos", "Todos")],
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(choices=[("enviada", "Enviada"), ("falha", "Falha")], max_length=20)),
                ("data_envio", models.DateTimeField()),
                ("erro", models.TextField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="notificacoes.notificationtemplate"
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Notificação",
                "verbose_name_plural": "Logs de Notificação",
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.BooleanField(default=True)),
                ("push", models.BooleanField(default=True)),
                ("whatsapp", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencias_notificacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferência de Notificação",
                "verbose_name_plural": "Preferências de Notificação",
            },
        ),
    ]
