# Generated by Django 5.2.5 on 2025-08-14 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0002_remove_pushsubscription_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationtemplate",
            old_name="created",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.RenameField(
            model_name="notificationtemplate",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RenameField(
            model_name="notificationlog",
            old_name="created",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.RenameField(
            model_name="notificationlog",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RenameField(
            model_name="historiconotificacao",
            old_name="created",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="historiconotificacao",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.RenameField(
            model_name="historiconotificacao",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="historiconotificacao",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="notificationlog",
            unique_together={("user", "template", "canal", "created_at")},
        ),
    ]
