# Generated by Django 5.2.2 on 2025-08-01 17:15

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0002_default_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="data_envio",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="status",
            field=models.CharField(
                choices=[("pendente", "Pendente"), ("enviada", "Enviada"), ("falha", "Falha")],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="assunto",
            field=models.CharField(max_length=200, verbose_name="Assunto"),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="canal",
            field=models.CharField(
                choices=[("email", "E-mail"), ("push", "Push"), ("whatsapp", "WhatsApp"), ("todos", "Todos")],
                max_length=20,
                verbose_name="Canal",
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="codigo",
            field=models.SlugField(unique=True, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="corpo",
            field=models.TextField(verbose_name="Corpo"),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="usernotificationpreference",
            name="email",
            field=models.BooleanField(default=True, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="usernotificationpreference",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="usernotificationpreference",
            name="push",
            field=models.BooleanField(default=True, verbose_name="Push"),
        ),
        migrations.AlterField(
            model_name="usernotificationpreference",
            name="whatsapp",
            field=models.BooleanField(default=True, verbose_name="WhatsApp"),
        ),
        migrations.AlterUniqueTogether(
            name="notificationlog",
            unique_together={("user", "template", "data_envio", "canal")},
        ),
    ]
