# Generated by Django 5.2.2 on 2025-08-07 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0002_pushsubscription_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pushsubscription",
            name="created",
        ),
        migrations.RemoveField(
            model_name="pushsubscription",
            name="modified",
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 7, 0, 0)),
            preserve_default=False,
        ),
    ]
