# Generated by Django 5.2.2 on 2025-08-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0003_alter_notificationlog_data_envio_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationtemplate",
            options={
                "permissions": [("can_send_notifications", "Can send notifications")],
                "verbose_name": "Template de Notificação",
                "verbose_name_plural": "Templates de Notificação",
            },
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="destinatario",
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
