# Generated by Django 5.2.5 on 2025-08-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0003_convert_notificacao_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationtemplate",
            name="ativo",
        ),
    ]
