# Generated by Django 5.2.5 on 2025-08-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0003_convert_notificacao_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationtemplate",
            name="ativo",
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
