# Generated by Django 5.2.5 on 2025-08-18 20:32

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0004_remove_notificationtemplate_ativo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="historiconotificacao",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="historiconotificacao",
            name="data_referencia",
            field=models.DateField(default=datetime.date(2025, 8, 18)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historiconotificacao",
            name="frequencia",
            field=models.CharField(
                choices=[("diaria", "Diária"), ("semanal", "Semanal")], default="diaria", max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="historiconotificacao",
            unique_together={("user", "canal", "frequencia", "data_referencia")},
        ),
    ]
