# Generated by Django 5.2.2 on 2025-08-04 18:22

import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0004_alter_notificationtemplate_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationtemplate",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="frequencia_email",
            field=models.CharField(
                choices=[("imediata", "Imediata"), ("diaria", "Diária"), ("semanal", "Semanal")],
                default="imediata",
                max_length=20,
                verbose_name="Frequência E-mail",
            ),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="frequencia_whatsapp",
            field=models.CharField(
                choices=[("imediata", "Imediata"), ("diaria", "Diária"), ("semanal", "Semanal")],
                default="imediata",
                max_length=20,
                verbose_name="Frequência WhatsApp",
            ),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationlog",
            unique_together={("user", "template", "canal", "created")},
        ),
    ]
