# Generated by Django 5.2.5 on 2024-04-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0004_remove_notificationtemplate_ativo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="data_leitura",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
