# Generated by Django 5.2.5 on 2025-08-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0005_add_notificationtemplate_ativo"),
        ("notificacoes", "0005_alter_historiconotificacao_unique_together_and_more"),
        ("notificacoes", "0005_alter_notificationlog_canal"),
        ("notificacoes", "0005_notificationlog_data_leitura"),
        ("notificacoes", "0005_pushsubscription_ativo"),
        ("notificacoes", "0005_usernotificationpreference"),
    ]

    operations = []
