# Generated by Django 5.2.2 on 2025-08-05 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0005_notificationtemplate_created_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserNotificationPreference",
        ),
    ]
