# Generated by Django 5.2.2 on 2025-08-06 14:42

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0006_delete_usernotificationpreference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoNotificacao",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "canal",
                    models.CharField(
                        choices=[("email", "E-mail"), ("push", "Push"), ("whatsapp", "WhatsApp"), ("todos", "Todos")],
                        max_length=20,
                    ),
                ),
                ("conteudo", models.JSONField(default=list)),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Histórico de Notificação",
                "verbose_name_plural": "Históricos de Notificação",
                "ordering": ["-enviado_em"],
                "unique_together": {("user", "canal", "enviado_em")},
            },
        ),
    ]
