# Generated by Django 5.2.5 on 2025-08-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0006_merge_20250818_1812"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationtemplate",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
    ]
