# Generated by Django 5.2.5 on 2025-08-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0007_alter_notificationtemplate_ativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="corpo_renderizado",
            field=models.TextField(blank=True, null=True),
        ),
    ]
