# Generated by Django 5.2.2 on 2025-08-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0008_pushsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="status",
            field=models.CharField(
                choices=[("pendente", "Pendente"), ("enviada", "Enviada"), ("falha", "Falha"), ("lida", "Lida")],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
