# Generated by Django 5.2.5 on 2025-09-03 21:50

from django.db import migrations


def create_template(apps, schema_editor):
    NotificationTemplate = apps.get_model("notificacoes", "NotificationTemplate")
    NotificationTemplate.objects.get_or_create(
        codigo="feed_new_post",
        defaults={
            "assunto": "Novo post no feed",
            "corpo": "Um novo post foi publicado no feed.",
            "canal": "push",
        },
    )


def remove_template(apps, schema_editor):
    NotificationTemplate = apps.get_model("notificacoes", "NotificationTemplate")
    NotificationTemplate.objects.filter(codigo="feed_new_post").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0008_add_corpo_renderizado_to_notificationlog"),
    ]

    operations = [
        migrations.RunPython(create_template, remove_template),
    ]
