# Generated by Django 5.2.5 on 2025-11-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0013_update_connection_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="historiconotificacao",
            name="canal",
            field=models.CharField(
                choices=[
                    ("email", "E-mail"),
                    ("push", "Push"),
                    ("whatsapp", "WhatsApp"),
                    ("app", "In-app"),
                    ("todos", "Todos"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="canal",
            field=models.CharField(
                choices=[("email", "E-mail"), ("push", "Push"), ("whatsapp", "WhatsApp"), ("app", "In-app")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="canal",
            field=models.CharField(
                choices=[
                    ("email", "E-mail"),
                    ("push", "Push"),
                    ("whatsapp", "WhatsApp"),
                    ("app", "In-app"),
                    ("todos", "Todos"),
                ],
                max_length=20,
                verbose_name="Canal",
            ),
        ),
    ]
