# Generated by Django 5.2.5 on 2025-08-08 18:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizacoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nome", models.CharField(default="", max_length=255)),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                ("tipo", models.CharField(default="", max_length=50)),
                ("municipio", models.CharField(default="", max_length=100)),
                ("estado", models.CharField(default="", max_length=2)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="empresas/logos/")),
                ("descricao", models.TextField(blank=True)),
                ("palavras_chave", models.TextField(blank=True)),
                ("validado_em", models.DateTimeField(blank=True, null=True)),
                ("fonte_validacao", models.CharField(blank=True, default="", max_length=50)),
                ("search_vector", models.TextField(blank=True, editable=False)),
                ("versao", models.PositiveIntegerField(default=1)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresas",
                        to="organizacoes.organizacao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="EmpresaChangeLog",
            fields=[
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("campo_alterado", models.CharField(max_length=50)),
                ("valor_antigo", models.TextField(blank=True)),
                ("valor_novo", models.TextField(blank=True)),
                ("alterado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="empresas.empresa"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-alterado_em"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=50, unique=True)),
                (
                    "categoria",
                    models.CharField(choices=[("prod", "Produto"), ("serv", "Serviço")], default="prod", max_length=4),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="empresas.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AddField(
            model_name="empresa",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="empresas", to="empresas.tag"),
        ),
        migrations.CreateModel(
            name="ContatoEmpresa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                ("cargo", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=20)),
                ("principal", models.BooleanField(default=False)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="contatos", to="empresas.empresa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contato da Empresa",
                "verbose_name_plural": "Contatos das Empresas",
                "unique_together": {("empresa", "email")},
            },
        ),
        migrations.CreateModel(
            name="AvaliacaoEmpresa",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nota", models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ("comentario", models.TextField(blank=True)),
                (
                    "usuario",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="avaliacoes", to="empresas.empresa"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("empresa", "usuario")},
            },
        ),
        migrations.CreateModel(
            name="FavoritoEmpresa",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="favoritos", to="empresas.empresa"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoritos_empresa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorito da Empresa",
                "verbose_name_plural": "Favoritos das Empresas",
                "unique_together": {("usuario", "empresa")},
            },
        ),
        migrations.AddIndex(
            model_name="empresa",
            index=models.Index(fields=["cnpj"], name="empresas_em_cnpj_fe5b68_idx"),
        ),
        migrations.AddIndex(
            model_name="empresa",
            index=models.Index(fields=["municipio"], name="empresas_em_municip_190863_idx"),
        ),
        migrations.AddIndex(
            model_name="empresa",
            index=models.Index(fields=["estado"], name="empresas_em_estado_440b9e_idx"),
        ),
        migrations.AddIndex(
            model_name="empresa",
            index=models.Index(fields=["deleted"], name="empresas_em_deleted_e09a62_idx"),
        ),
        migrations.AddIndex(
            model_name="empresa",
            index=models.Index(fields=["search_vector"], name="empresas_em_search__eaa578_idx"),
        ),
    ]
