# Generated by Django 5.2.4 on 2025-07-15 18:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizacoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=50, unique=True)),
                (
                    "categoria",
                    models.CharField(choices=[("prod", "Produto"), ("serv", "Serviço")], default="prod", max_length=4),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                ("nome", models.CharField(max_length=255)),
                ("tipo", models.CharField(max_length=100)),
                ("municipio", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="empresas/logos/")),
                ("descricao", models.TextField(blank=True)),
                ("contato", models.CharField(blank=True, max_length=255)),
                ("palavras_chave", models.CharField(blank=True, max_length=255)),
                (
                    "organizacao",
                    models.ForeignKey(
                        blank=True,
                        db_column="organization",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresas",
                        to="organizacoes.organizacao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, related_name="empresas", to="empresas.tag")),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
    ]
