# Generated by Django 5.2.2 on 2025-07-15 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("organizacoes", "__first__"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="organizacao",
            field=models.ForeignKey(
                db_column="organization",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="empresas",
                to="organizacoes.organizacao",
            ),
        ),
    ]
