# Generated by Django 5.2.2 on 2025-07-25 20:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="empresa",
            options={"ordering": ["nome"], "verbose_name": "Empresa", "verbose_name_plural": "Empresas"},
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="cep",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="cidade",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="email_corporativo",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="endereco",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="nome_fantasia",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="ramo_atividade",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="razao_social",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="rede_social",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="site",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="telefone_corporativo",
        ),
        migrations.AddField(
            model_name="empresa",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="empresa",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="municipio",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="empresa",
            name="nome",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="empresa",
            name="palavras_chave",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="tipo",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="estado",
            field=models.CharField(default="", max_length=2),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="EmpresaChangeLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("campo_alterado", models.CharField(max_length=50)),
                ("valor_antigo", models.TextField(blank=True)),
                ("valor_novo", models.TextField(blank=True)),
                ("alterado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="empresas.empresa"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-alterado_em"],
            },
        ),
        migrations.CreateModel(
            name="AvaliacaoEmpresa",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nota", models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ("comentario", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="avaliacoes", to="empresas.empresa"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("empresa", "usuario")},
            },
        ),
    ]
