# Generated by Django 5.2.2 on 2025-06-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_load_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="categoria",
            field=models.CharField(
                choices=[("prod", "Produto"), ("serv", "Serviço")],
                default="prod",
                max_length=4,
            ),
        ),
    ]
