# Generated by Django 5.2.5 on 2025-08-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_alter_empresachangelog_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contatoempresa",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="contatoempresa",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contatoempresa",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="contatoempresa",
            unique_together={("empresa", "email", "deleted")},
        ),
    ]
