# Generated by Django 5.2.2 on 2025-08-01 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_alter_empresa_options_remove_empresa_banner_and_more"),
        ("organizacoes", "0004_organizacao_cidade_organizacao_contato_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="empresa",
            index=models.Index(fields=["cnpj"], name="empresas_em_cnpj_fe5b68_idx"),
        ),
        migrations.AddIndex(
            model_name="empresa",
            index=models.Index(fields=["municipio"], name="empresas_em_municip_190863_idx"),
        ),
        migrations.AddIndex(
            model_name="empresa",
            index=models.Index(fields=["estado"], name="empresas_em_estado_440b9e_idx"),
        ),
    ]
