# Generated by Django 5.2.2 on 2025-08-02 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0003_empresa_empresas_em_cnpj_fe5b68_idx_and_more"),
        ("organizacoes", "0004_organizacao_cidade_organizacao_contato_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="empresa",
            index=models.Index(fields=["deleted"], name="empresas_em_deleted_e09a62_idx"),
        ),
    ]
