# Generated by Django 5.2.5 on 2025-08-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0004_tag_deleted_tag_deleted_at"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contatoempresa",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False), ("principal", True)),
                fields=("empresa",),
                name="unique_principal_contatoempresa",
            ),
        ),
    ]
