# Generated by Django 5.2.2 on 2025-08-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0005_alter_avaliacaoempresa_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avaliacaoempresa",
            options={"ordering": ["-created"]},
        ),
    ]
