# Generated by Django 5.2.5 on 2025-09-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0005_contatoempresa_unique_principal_contatoempresa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="logo",
        ),
        migrations.AddField(
            model_name="empresa",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="empresas/avatars/"),
        ),
        migrations.AddField(
            model_name="empresa",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="empresas/covers/"),
        ),
    ]
