# Generated by Django 5.2.2 on 2025-08-04 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0006_alter_avaliacaoempresa_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avaliacaoempresa",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="empresachangelog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="avaliacaoempresa",
            name="created",
        ),
        migrations.RemoveField(
            model_name="avaliacaoempresa",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="empresachangelog",
            name="alterado_em",
        ),
        migrations.AddField(
            model_name="avaliacaoempresa",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="avaliacaoempresa",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="avaliacaoempresa",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="avaliacaoempresa",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empresachangelog",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="empresachangelog",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="empresachangelog",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empresachangelog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
