# Generated by Django 5.2.2 on 2025-08-04 22:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0007_alter_avaliacaoempresa_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="empresachangelog",
            options={"ordering": ["-alterado_em"]},
        ),
        migrations.RemoveField(
            model_name="empresachangelog",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="empresachangelog",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="empresachangelog",
            name="alterado_em",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
