# Generated by Django 5.2.2 on 2025-08-06 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0008_alter_empresachangelog_options_and_more"),
        ("organizacoes", "0008_organizacaoatividadelog_organizacaochangelog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="search_vector",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddIndex(
            model_name="empresa",
            index=models.Index(fields=["search_vector"], name="empresas_em_search__eaa578_idx"),
        ),
    ]
