# Generated by Django 5.2.2 on 2025-08-07 17:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0012_empresa_validacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoritoempresa",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
