# Generated by Django 5.2.4 on 2025-07-15 18:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nucleos", "__first__"),
        ("organizacoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenAcesso",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "tipo_destino",
                    models.CharField(
                        choices=[("admin", "admin"), ("gerente", "gerente"), ("cliente", "cliente")], max_length=10
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("novo", "não usado"), ("usado", "usado"), ("expirado", "expirado")],
                        default="novo",
                        max_length=10,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_expiracao", models.DateTimeField()),
                (
                    "gerado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens_gerados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nucleo_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens",
                        to="nucleos.nucleo",
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        blank=True,
                        db_column="organization",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="organizacoes.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Acesso",
                "verbose_name_plural": "Tokens de Acesso",
                "db_table": "accounts_tokenacesso",
            },
        ),
    ]
