# Generated by Django 5.2.2 on 2025-07-19 16:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nucleos", "0001_initial"),
        ("organizacoes", "0002_alter_organizacao_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigoAutenticacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=8)),
                ("expira_em", models.DateTimeField()),
                ("verificado", models.BooleanField(default=False)),
                ("tentativas", models.PositiveSmallIntegerField(default=0)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codigos_autenticacao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenAcesso",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codigo",
                    models.CharField(
                        default="9df0d0d40193479d92bd7e46f15e27be", editable=False, max_length=32, unique=True
                    ),
                ),
                (
                    "tipo_destino",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("associado", "Associado"),
                            ("nucleado", "Nucleado"),
                            ("coordenador", "Coordenador"),
                            ("convidado", "Convidado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("novo", "Não usado"), ("usado", "Usado"), ("expirado", "Expirado")],
                        default="novo",
                        max_length=10,
                    ),
                ),
                ("data_expiracao", models.DateTimeField(blank=True, null=True)),
                (
                    "gerado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tokens_gerados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nucleos", models.ManyToManyField(blank=True, related_name="tokens", to="nucleos.nucleo")),
                (
                    "organizacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="organizacoes.organizacao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens_recebidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TOTPDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("secret", models.CharField(max_length=32)),
                ("confirmado", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totp_device",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
