# Generated by Django 5.2.5 on 2025-08-08 18:44

import core.fields
import django.db.models.deletion
import django.utils.timezone
import tokens.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nucleos", "0001_initial"),
        ("organizacoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("client_name", models.CharField(blank=True, max_length=100)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "scope",
                    models.CharField(choices=[("read", "Read"), ("write", "Write"), ("admin", "Admin")], max_length=20),
                ),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CodigoAutenticacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=8)),
                ("expira_em", models.DateTimeField()),
                ("verificado", models.BooleanField(default=False)),
                ("tentativas", models.PositiveSmallIntegerField(default=0)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codigos_autenticacao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenAcesso",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codigo",
                    models.CharField(
                        default=tokens.models.generate_hex_uuid, editable=False, max_length=32, unique=True
                    ),
                ),
                (
                    "tipo_destino",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("associado", "Associado"),
                            ("nucleado", "Nucleado"),
                            ("coordenador", "Coordenador"),
                            ("convidado", "Convidado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("novo", "Não usado"),
                            ("usado", "Usado"),
                            ("expirado", "Expirado"),
                            ("revogado", "Revogado"),
                        ],
                        default="novo",
                        max_length=10,
                    ),
                ),
                ("data_expiracao", models.DateTimeField(blank=True, null=True)),
                ("ip_gerado", models.CharField(blank=True, max_length=45, null=True)),
                ("ip_utilizado", models.CharField(blank=True, max_length=45, null=True)),
                ("revogado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "gerado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tokens_gerados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nucleos", models.ManyToManyField(blank=True, related_name="tokens", to="nucleos.nucleo")),
                (
                    "organizacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="organizacoes.organizacao",
                    ),
                ),
                (
                    "revogado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens_revogados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens_recebidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenUsoLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("geracao", "Geração"),
                            ("validacao", "Validação"),
                            ("uso", "Uso"),
                            ("revogacao", "Revogação"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip", core.fields.EncryptedCharField(blank=True, max_length=128, null=True)),
                ("user_agent", core.fields.EncryptedCharField(blank=True, max_length=512, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="tokens.tokenacesso"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TOTPDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("secret", models.CharField(max_length=32)),
                ("confirmado", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totp_device",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
