# Generated by Django 5.2.2 on 2025-07-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenacesso",
            name="codigo",
            field=models.CharField(
                default="bd43e03965cc412d8be8f4b09499348a", editable=False, max_length=32, unique=True
            ),
        ),
    ]
