# Generated by Django 5.2.2 on 2025-07-15 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "__first__"),
        ("organizacoes", "__first__"),
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenacesso",
            name="nucleos",
            field=models.ManyToManyField(blank=True, related_name="tokens", to="nucleos.nucleo"),
        ),
        migrations.AlterField(
            model_name="tokenacesso",
            name="nucleo_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="token_destino",
                to="nucleos.nucleo",
            ),
        ),
        migrations.AlterField(
            model_name="tokenacesso",
            name="organizacao",
            field=models.ForeignKey(
                db_column="organization",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens",
                to="organizacoes.organizacao",
            ),
        ),
    ]
