# Generated by Django 5.2.5 on 2025-08-14 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tokenusolog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="tokenusolog",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="tokenusolog",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="tokenusolog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
