# Generated by Django 5.2.2 on 2025-07-15 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacoes", "0002_organizacao_created_at_organizacao_updated_at"),
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenacesso",
            name="organizacao",
            field=models.ForeignKey(
                blank=True,
                db_column="organization",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens",
                to="organizacoes.organizacao",
            ),
        ),
    ]
