# Generated by Django 5.2.4 on 2025-07-15 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "__first__"),
        ("organizacoes", "0001_initial"),
        ("tokens", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tokenacesso",
            name="nucleo_destino",
        ),
        migrations.AddField(
            model_name="tokenacesso",
            name="nucleos",
            field=models.ManyToManyField(related_name="tokens_acesso", to="nucleos.nucleo"),
        ),
        migrations.AddField(
            model_name="tokenacesso",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens_acesso",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tokenacesso",
            name="organizacao",
            field=models.ForeignKey(
                db_column="organization",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens",
                to="organizacoes.organizacao",
            ),
        ),
    ]
