# Generated by Django 5.2.5 on 2025-08-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0002_alter_tokenusolog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenacesso",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tokenacesso",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
