# Generated by Django 5.2.2 on 2025-07-19 18:55

import tokens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0002_alter_tokenacesso_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenacesso",
            name="codigo",
            field=models.CharField(default=tokens.models.generate_hex_uuid, editable=False, max_length=32, unique=True),
        ),
    ]
