# Generated by Django 5.2.5 on 2025-08-14 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0002_alter_tokenusolog_options_and_more"),
    ]

    # No-op migration left for compatibility after resolving merge
    # conflicts. The soft delete fields for ``TokenAcesso`` are added in
    # ``0003_apitoken_deleted_apitoken_deleted_at_and_more``.
    operations = []
