# Generated by Django 5.2.4 on 2025-07-15 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleos", "__first__"),
        ("tokens", "0002_remove_tokenacesso_nucleo_destino_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenacesso",
            name="nucleos",
            field=models.ManyToManyField(blank=True, related_name="tokens_acesso", to="nucleos.nucleo"),
        ),
        migrations.AlterField(
            model_name="tokenacesso",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens_acesso",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
