# Generated by Django 5.2.2 on 2025-07-25 21:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0003_alter_tokenacesso_codigo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenacesso",
            name="ip_gerado",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tokenacesso",
            name="ip_utilizado",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tokenacesso",
            name="revogado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tokenacesso",
            name="revogado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tokens_revogados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tokenacesso",
            name="estado",
            field=models.CharField(
                choices=[("novo", "Não usado"), ("usado", "Usado"), ("expirado", "Expirado"), ("revogado", "Revogado")],
                default="novo",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="TokenUsoLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("geracao", "Geração"),
                            ("validacao", "Validação"),
                            ("uso", "Uso"),
                            ("revogacao", "Revogação"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=256, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="tokens.tokenacesso"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
