# Generated by Django 5.2.5 on 2025-08-14 22:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0003_apitoken_deleted_apitoken_deleted_at_and_more"),
        ("tokens", "0003_tokenacesso_deleted_tokenacesso_deleted_at"),
    ]

    operations = []
