# Generated by Django 5.2.2 on 2025-07-26 16:17

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0004_tokenacesso_ip_gerado_tokenacesso_ip_utilizado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenusolog",
            name="ip",
            field=core.fields.EncryptedCharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="tokenusolog",
            name="user_agent",
            field=core.fields.EncryptedCharField(blank=True, max_length=512, null=True),
        ),
    ]
