# Generated by Django 5.2.2 on 2025-08-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0006_apitoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenacesso",
            name="ip_gerado",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name="tokenacesso",
            name="ip_utilizado",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
