# Generated by Django 5.2.5 on 2025-08-19 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0006_apitoken_revogado_por"),
        ("tokens", "0006_apitokenlog"),
        ("tokens", "0006_codigoautenticacao_hash_totpdevice_encrypt"),
    ]

    operations = []
