# Generated by Django 5.2.5 on 2025-08-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0008_rehash_tokenacesso_sha256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
