# Generated by Django 5.2.5 on 2025-08-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0009_alter_apitoken_expires_at"),
        ("tokens", "0009_codigoautenticacaolog"),
    ]

    operations = []
