# Generated by Django 5.2.5 on 2025-08-21 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0010_merge_20250821_1452"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="anterior",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substituido_por",
                to="tokens.apitoken",
            ),
        ),
    ]
