# Generated by Django 5.2.5 on 2025-08-21 17:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0010_merge_20250821_1454"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiTokenIp",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ip", models.GenericIPAddressField()),
                ("tipo", models.CharField(choices=[("permitido", "Permitido"), ("negado", "Negado")], max_length=10)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ips", to="tokens.apitoken"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("token", "ip", "tipo")},
            },
        ),
    ]
