# Generated by Django 5.2.5 on 2025-08-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0010_apitoken_device_fingerprint"),
        ("tokens", "0011_apitoken_anterior"),
        ("tokens", "0011_apitokenip"),
        ("tokens", "0011_tokenwebhookevent"),
    ]

    operations = []
