# Generated by Django 5.2.5 on 2025-08-23 16:51

import core.fields
from django.db import migrations


def encrypt_ips(apps, schema_editor):
    TokenAcesso = apps.get_model("tokens", "TokenAcesso")
    for token in TokenAcesso.objects.all():
        update_fields = []
        if token.ip_gerado and not token.ip_gerado.startswith("gAAAA"):
            token.ip_gerado = token.ip_gerado
            update_fields.append("ip_gerado")
        if token.ip_utilizado and not token.ip_utilizado.startswith("gAAAA"):
            token.ip_utilizado = token.ip_utilizado
            update_fields.append("ip_utilizado")
        if update_fields:
            token.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0014_codigoautenticacaolog_envio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenacesso",
            name="ip_gerado",
            field=core.fields.EncryptedCharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="tokenacesso",
            name="ip_utilizado",
            field=core.fields.EncryptedCharField(blank=True, max_length=128, null=True),
        ),
        migrations.RunPython(encrypt_ips, migrations.RunPython.noop),
    ]
