# Generated by Django 5.2.5 on 2025-08-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0007_totpdevice_hash_secret"),
        ("tokens", "0015_alter_tokenacesso_ip_gerado_and_more"),
    ]

    operations = []
