# Generated by Django 5.2.5 on 2025-09-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0016_merge_20250828_1207"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apitokenlog",
            name="token",
        ),
        migrations.RemoveField(
            model_name="apitokenip",
            name="token",
        ),
        migrations.AlterUniqueTogether(
            name="apitokenip",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="apitokenlog",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="ApiToken",
        ),
        migrations.DeleteModel(
            name="ApiTokenIp",
        ),
        migrations.DeleteModel(
            name="ApiTokenLog",
        ),
    ]
