# Generated by Django 5.2.5 on 2025-09-19 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0016_merge_20250828_1207"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApiTokenLog",
        ),
        migrations.DeleteModel(
            name="ApiTokenIp",
        ),
        migrations.DeleteModel(
            name="ApiToken",
        ),
    ]
