# Generated by Django 5.2.5 on 2025-09-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0017_remove_apitokenlog_token_remove_apitokenip_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tokenacesso",
            name="nucleos",
        ),
        migrations.AlterField(
            model_name="tokenacesso",
            name="tipo_destino",
            field=models.CharField(choices=[("associado", "Associado"), ("convidado", "Convidado")], max_length=20),
        ),
    ]
