# Generated by Django 5.2.5 on 2025-09-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0018_remove_tokenacesso_nucleos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenacesso",
            name="codigo_preview",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
