# Generated by Django 5.2.5 on 2026-03-05 22:44

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0020_totpdevice_base32_secrets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="totpdevice",
            name="secret",
            field=core.fields.EncryptedCharField(max_length=512),
        ),
    ]
