# Generated by Django 5.2.5 on 2026-03-05 22:54

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0021_alter_totpdevice_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codigoautenticacaolog",
            name="ip",
            field=core.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tokenacesso",
            name="ip_gerado",
            field=core.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tokenacesso",
            name="ip_utilizado",
            field=core.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tokenusolog",
            name="ip",
            field=core.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="totpdevice",
            name="secret",
            field=core.fields.EncryptedTextField(),
        ),
    ]
